/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status des Servers */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alle Produkte, sortiert nach Name */
        get: operations["listProducts"];
        put?: never;
        /**
         * Produkt manuell anlegen
         * @description Fehler-code: invalid_request (400), barcode_in_use (409), invalid_barcode (422).
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Ein Produkt
         * @description Fehler-code: not_found (404).
         */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        /**
         * Produkt mit Barcodes, Buchungen und Bild löschen
         * @description Fehler-code: not_found (404).
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /**
         * Produkt ändern (JSON Merge Patch)
         * @description Fehler-code: invalid_request (400), not_found (404).
         */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/products/{id}/barcodes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Barcode einem Produkt zuordnen
         * @description Fehler-code: invalid_request (400), not_found (404), barcode_in_use (409), invalid_barcode (422).
         */
        post: operations["addBarcode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/barcodes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                /** @description Barcode, wird vor dem Vergleich normalisiert. */
                code: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Barcode von einem Produkt entfernen
         * @description Fehler-code: not_found (404), auch bei ungültigem Barcode.
         */
        delete: operations["removeBarcode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID des Produkts, das in das Zielprodukt überführt und danach gelöscht wird. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Produkt in ein anderes Produkt überführen
         * @description Barcodes und Buchungen des Produkts id gehen auf das Zielprodukt über. Hat das Produkt id Bestand, bekommt das Ziel eine Buchung mit kind merge und delta gleich diesem Bestand; ohne Bestand gibt es keine Buchung. Hat das Ziel keine Kastengröße (crate_size), übernimmt es die des Produkts id. Danach wird das Produkt id mit seinem Bild gelöscht. Die übrigen Felder des Ziels bleiben unverändert. Fehler-code: invalid_request (400, auch wenn Ziel und Quelle gleich sind), not_found (404).
         */
        post: operations["mergeProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Produktbild
         * @description Fehler-code: not_found (404), auch wenn das Produkt kein Bild hat oder die Bilddatei fehlt.
         */
        get: operations["getProductImage"];
        /**
         * Eigenes Foto als Produktbild hochladen
         * @description Der Body ist das Bild, höchstens 2 MB. Erlaubt sind image/jpeg, image/png und image/webp; der Typ wird am Inhalt erkannt, nicht am Content-Type. Ein vorhandenes Bild wird ersetzt und die Bildquelle von Open Food Facts entfernt. Fehler-code: invalid_request (400), not_found (404), invalid_image (422, größer als 2 MB oder kein JPEG, PNG oder WebP).
         */
        put: operations["uploadProductImage"];
        post?: never;
        /**
         * Produktbild und Bildquelle entfernen
         * @description Entfernt die Bilddatei und die Bildquelle von Open Food Facts, damit das Bild nicht erneut geladen wird. Ein Produkt ohne Bild ist kein Fehler. Fehler-code: not_found (404).
         */
        delete: operations["deleteProductImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/recognition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Name, Marke und Menge vom Produktfoto lesen
         * @description Schickt das gespeicherte Produktfoto an den eingerichteten Anbieter (ADR-0021) und gibt zurück, was er auf der Packung liest. Am Produkt ändert sich nichts. Die Werte sind getrimmt und auf die Längen des Produkts gekürzt (name und brand 120, package_size 40 Zeichen); was auf dem Foto nicht lesbar ist, ist null. Fehler-code: not_found (404), recognition_disabled (409, kein Anbieter eingerichtet), no_image (409, das Produkt hat kein Foto), invalid_api_key (422, der Anbieter nimmt den Schlüssel nicht an), recognition_failed (502, der Anbieter ist nicht erreichbar oder liefert keine brauchbare Antwort).
         */
        post: operations["recognizeProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buchungen, neueste zuerst
         * @description Sortiert nach id absteigend, seitenweise über cursor. Ein unbekanntes product_id ergibt eine leere Liste. Fehler-code: invalid_request (400).
         */
        get: operations["listMovements"];
        put?: never;
        /**
         * Buchung anlegen
         * @description Fehler-code: invalid_request (400), not_found (404), unknown_barcode (404), stock_already_zero (409), invalid_barcode (422), idempotency_key_mismatch (422).
         */
        post: operations["createMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movements/{id}/reversal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID der Buchung, die storniert wird. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Buchung stornieren
         * @description Legt eine Buchung mit kind reversal an, die die Änderung der Buchung id zurücknimmt. Würde der Bestand negativ, wird er 0 mit der Warnung clamped_to_zero; delta ist die tatsächliche Änderung. Buchungen der Arten reversal und merge sind nicht stornierbar. Fehler-code: invalid_request (400), not_found (404), already_reversed (409), not_reversible (409), idempotency_key_mismatch (422).
         */
        post: operations["reverseMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Einkaufsliste, sortiert nach Name
         * @description Alle Produkte mit missing größer 0 oder mit Vormerkung (marked), sortiert nach Name ohne Beachtung der Groß- und Kleinschreibung.
         */
        get: operations["getShoppingList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-list/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Produkt für den Einkauf vormerken
         * @description Merkt das Produkt für den Einkauf vor (marked true), bestimmt über product_id oder barcode. Ändert nie den Bestand und legt keine Buchung an. Ein unbekannter Barcode legt das Produkt wie beim Einlagern an, aber ohne Buchung, also mit Bestand 0, und merkt es vor. Ein schon vorgemerktes Produkt bleibt unverändert. Fehler-code: invalid_request (400), not_found (404), invalid_barcode (422).
         */
        post: operations["markShoppingItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-list/items/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID des Produkts, dessen Vormerkung entfernt wird. */
                product_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Vormerkung entfernen
         * @description Setzt marked auf false. Ein Fehlbestand nach Soll bleibt auf der Einkaufsliste. Ein nicht vorgemerktes Produkt bleibt unverändert. Fehler-code: not_found (404).
         */
        delete: operations["unmarkShoppingItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-list/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Einkaufsliste per MQTT neu senden
         * @description Fordert das Ereignis shopping.snapshot an: alle Produkte mit Soll größer 0 oder mit Vormerkung, für die gewählte Zielliste. Es geht über die Outbox per MQTT hinaus. Mehrere Anfragen innerhalb von 2 s ergeben einen Snapshot. Fehler-code: mqtt_disabled (409, ohne MQTT).
         */
        post: operations["sendShoppingSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Zusammenfassung des Vorrats
         * @description Zählungen über alle Produkte und die ersten 100 Einträge der Einkaufsliste. Immer verfügbar, auch ohne MQTT. Mit MQTT geht dasselbe JSON retained auf <MQTT_TOPIC_PREFIX>/state/summary hinaus.
         */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Zustand für die Einstellungen
         * @description Version, Größe der Datenbank, die regelmäßigen Backups in DATA_DIR/backups und ob Open Food Facts eingerichtet ist. Verbindungsdaten und Geheimnisse gibt der Endpunkt nicht aus.
         */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backup herunterladen
         * @description Frisches Backup als tar-Archiv mit gzip: stashbert.db (eine Kopie per VACUUM INTO) und der Ordner images/ mit allen Bilddateien. Gleichzeitige Downloads laufen nacheinander. Ohne Anmeldung (ADR-0013) kann das jeder im Heimnetz; eingespielt wird das Archiv mit POST /backup/restore.
         */
        get: operations["downloadBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backup einspielen
         * @description Der Body ist ein Archiv aus GET /backup, höchstens 1 GB, mit dem Content-Type application/gzip (application/x-gzip geht auch). Es darf nur stashbert.db und Bilder unter images/ enthalten und entpackt höchstens 4 GB groß sein. StashBert prüft das Archiv und legt es in DATA_DIR/restore/pending bereit, ohne den laufenden Betrieb zu ändern. Nach der Antwort startet StashBert im selben Prozess neu und spielt es vor dem Öffnen der Datenbank ein; der bisherige Stand bleibt in DATA_DIR/vor-restore-<YYYYMMDD-HHMMSS>. Ohne Anmeldung (ADR-0013) kann das jeder im Heimnetz (ADR-0020). Fehler-code: invalid_request (400, anderer Content-Type), invalid_backup (422, kein Backup von StashBert oder beschädigt), backup_too_new (422, von einer neueren Version), backup_too_large (413, größer als 1 GB oder entpackt größer als 4 GB), restore_in_progress (409, es wird schon ein Backup eingespielt).
         */
        post: operations["restoreBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/mqtt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * MQTT-Verbindung und Zielliste
         * @description Zustand der Verbindung zum Broker, die von Home Assistant auf <MQTT_TOPIC_PREFIX>/in/targets angebotenen Ziellisten und die gewählte Zielliste. Immer verfügbar, auch ohne MQTT (dann status disabled und keine angebotenen Listen).
         */
        get: operations["getMqttStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/mqtt/target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Zielliste wählen
         * @description Wählt die Liste in Home Assistant, in die die Einkaufsliste geht, oder hebt die Wahl mit id null auf. Beim Wechsel geht zuerst ein shopping.snapshot hinaus, der die alte Liste abräumt (falls eine gewählt war), danach einer für die neue Liste (falls es eine gibt). Dieselbe Liste erneut zu wählen ändert nichts. Fehler-code: invalid_request (400), mqtt_disabled (409, ohne MQTT), unknown_target (422, die id ist nicht im aktuellen Angebot).
         */
        put: operations["setShoppingTarget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/recognition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Einstellungen der Produkterkennung
         * @description Anbieter, Modell, ob ein API-Schlüssel gesetzt ist und seine letzten vier Zeichen, dazu die Standardmodelle (ADR-0021). Den Schlüssel selbst gibt kein Endpunkt aus.
         */
        get: operations["getRecognitionSettings"];
        /**
         * Produkterkennung einrichten oder abschalten
         * @description Setzt Anbieter, Modell und API-Schlüssel (ADR-0021). provider null schaltet ab und löscht Modell und Schlüssel. Ohne api_key bleibt ein gesetzter Schlüssel, wenn der Anbieter gleich bleibt; ein anderer Anbieter braucht einen neuen Schlüssel. Ein neuer Schlüssel wird mit der Modell-Liste des Anbieters geprüft und erst danach gespeichert. Ohne Anmeldung (ADR-0013) kann das jeder im Heimnetz. Fehler-code: invalid_request (400, auch ein neuer Anbieter ohne api_key), invalid_api_key (422, der Anbieter nimmt den Schlüssel nicht an), recognition_failed (502, der Anbieter ist nicht erreichbar).
         */
        put: operations["setRecognitionSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Fehler nach RFC 9457 mit zusätzlichem Feld code. */
        Problem: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
            code: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        Barcode: {
            /** @description Normalisierter Barcode. */
            code: string;
            /** @description Stückzahl, die ein Scan dieses Barcodes bucht. */
            units: number;
        };
        Product: {
            id: string;
            name: string;
            brand: string | null;
            package_size: string | null;
            note: string | null;
            /** @description Bestand. Nur lesen, er ändert sich nur durch Buchungen. */
            stock: number;
            /** @description Sollbestand. */
            target: number;
            /** @description Mindestbestand. Ohne Wert gilt der Sollbestand als Schwelle. */
            min_stock: number | null;
            /** @description Fehlmenge für die Einkaufsliste. Nur lesen, wird berechnet. */
            missing: number;
            /** @description Für den Einkauf vorgemerkt. Nur lesen; eine Buchung add beendet die Vormerkung. */
            marked: boolean;
            needs_review: boolean;
            /** @enum {string} */
            origin: "openfoodfacts" | "openbeautyfacts" | "openpetfoodfacts" | "openproductsfacts" | "manual" | "placeholder";
            /** @enum {string} */
            lookup_state: "none" | "pending" | "done" | "not_found";
            has_image: boolean;
            /** @description Flaschen pro Kasten. null, wenn das Produkt nicht in Kästen gekauft wird. Bestand und Sollbestand bleiben in Flaschen. */
            crate_size: number | null;
            /** @description Barcodes, sortiert nach Code. */
            barcodes: components["schemas"]["Barcode"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProductList: {
            items: components["schemas"]["Product"][];
        };
        BarcodeInput: {
            /** @description EAN-8, UPC-A, EAN-13 oder GTIN-14. Wird normalisiert gespeichert. */
            code: string;
            /**
             * @description Stückzahl, die ein Scan dieses Barcodes bucht.
             * @default 1
             */
            units?: number;
        };
        ProductCreate: {
            /** @description Wird getrimmt, danach 1 bis 120 Zeichen. */
            name: string;
            /** @description Wird getrimmt, danach höchstens 120 Zeichen. Leer wird null. */
            brand?: string;
            /** @description Wird getrimmt, danach höchstens 40 Zeichen. Leer wird null. */
            package_size?: string;
            /**
             * @description Sollbestand.
             * @default 0
             */
            target?: number;
            /** @description Mindestbestand, höchstens target. */
            min_stock?: number;
            /** @description Wird getrimmt, danach höchstens 500 Zeichen. Leer wird null. */
            note?: string;
            /** @description Flaschen pro Kasten. Ohne Wert oder null wird das Produkt nicht in Kästen gekauft. */
            crate_size?: number | null;
            /** @description Barcodes des Produkts. Jeder Code darf nur einmal vorkommen. */
            barcodes?: components["schemas"]["BarcodeInput"][];
        };
        /** @description JSON Merge Patch. Ein fehlendes Feld bleibt unverändert, null löscht ein nullbares Feld. needs_review wird false, wenn der Patch name, brand oder package_size enthält. */
        ProductPatch: {
            /** @description Wird getrimmt, danach 1 bis 120 Zeichen. */
            name?: string;
            /** @description Wird getrimmt, danach höchstens 120 Zeichen. Leer wird null. */
            brand?: string | null;
            /** @description Wird getrimmt, danach höchstens 40 Zeichen. Leer wird null. */
            package_size?: string | null;
            /** @description Sollbestand. */
            target?: number;
            /** @description Mindestbestand, nach dem Ändern höchstens target. */
            min_stock?: number | null;
            /** @description Wird getrimmt, danach höchstens 500 Zeichen. Leer wird null. */
            note?: string | null;
            /** @description Flaschen pro Kasten. null löscht die Kastengröße. */
            crate_size?: number | null;
        };
        ProductMerge: {
            /** @description ID des Zielprodukts. Muss sich von der ID der Quelle unterscheiden. */
            target_product_id: string;
        };
        /** @description Buchung für ein Produkt, bestimmt über product_id oder barcode. Genau eines der beiden Felder muss gesetzt sein, sonst invalid_request. quantity gilt für add und consume, stock ist bei inventory Pflicht und bei add und consume nicht erlaubt. */
        MovementCreate: {
            product_id?: string;
            /** @description EAN-8, UPC-A, EAN-13 oder GTIN-14, wird normalisiert. Die Menge für add und consume ist quantity × units des Barcodes; inventory ignoriert units. */
            barcode?: string;
            /** @enum {string} */
            kind: "add" | "consume" | "inventory";
            /**
             * @description Menge für add und consume.
             * @default 1
             */
            quantity?: number;
            /** @description Neuer Bestand für inventory. */
            stock?: number;
        };
        Movement: {
            id: string;
            product_id: string;
            /** @enum {string} */
            kind: "add" | "consume" | "inventory" | "reversal" | "merge";
            /** @description Tatsächliche Änderung des Bestands, darf 0 sein. */
            delta: number;
            /** @description Bestand nach der Buchung. */
            stock_after: number;
            /** @description Normalisierter Barcode, falls per Barcode gebucht wurde. */
            barcode: string | null;
            /** @description ID der stornierten Buchung, nur bei kind reversal. */
            reverses_id: string | null;
            /** Format: date-time */
            created_at: string;
        };
        MovementList: {
            /** @description Buchungen, sortiert nach id absteigend. */
            items: components["schemas"]["Movement"][];
            /** @description cursor für die nächste Seite, null auf der letzten Seite. */
            next_cursor: string | null;
        };
        MovementResult: {
            movement: components["schemas"]["Movement"];
            product: components["schemas"]["Product"];
            /** @description true, wenn das Produkt mit dieser Buchung angelegt wurde. */
            product_created: boolean;
            /** @description Hinweise zur Buchung, z. B. clamped_to_zero, wenn der Bestand auf 0 begrenzt wurde. */
            warnings: string[];
            /** @description Fertiger deutscher Anzeigetext, z. B. "Kidneybohnen 3 → 2". */
            message: string;
        };
        ShoppingItem: {
            product_id: string;
            name: string;
            brand: string | null;
            /** @description Fehlmenge, die gekauft werden muss. 0 bei einem vorgemerkten Produkt ohne Fehlbestand. */
            missing: number;
            /** @description Bestand. */
            stock: number;
            /** @description Sollbestand. */
            target: number;
            /** @description Für den Einkauf vorgemerkt. Nur lesen. */
            marked: boolean;
            /** @description Flaschen pro Kasten oder null. missing, stock und target bleiben in Flaschen. */
            crate_size: number | null;
        };
        /** @description Vormerkung für ein Produkt, bestimmt über product_id oder barcode. Genau eines der beiden Felder muss gesetzt sein, sonst invalid_request. */
        MarkCreate: {
            product_id?: string;
            /** @description EAN-8, UPC-A, EAN-13 oder GTIN-14, wird normalisiert. */
            barcode?: string;
        };
        MarkResult: {
            product: components["schemas"]["Product"];
            /** @description true, wenn das Produkt für einen unbekannten Barcode angelegt wurde. */
            product_created: boolean;
            /** @description true, wenn das Produkt schon vorher auf der Einkaufsliste stand, wegen missing größer 0 oder marked. */
            already_listed: boolean;
            /** @description Fertiger deutscher Anzeigetext: "Vorgemerkt: <name>", "Neu vorgemerkt: <name>" oder "Schon auf der Liste: <name>". */
            message: string;
        };
        ShoppingList: {
            items: components["schemas"]["ShoppingItem"][];
        };
        Summary: {
            /** @description Alle Produkte. */
            product_count: number;
            /** @description Einträge der Einkaufsliste (missing größer 0 oder marked). */
            shopping_count: number;
            /** @description Produkte mit Bestand 0, wie der Filter „Leer". */
            empty_count: number;
            /** @description Produkte mit needs_review, wie der Filter „Prüfen". */
            review_count: number;
            /** @description Die ersten 100 Einträge der Einkaufsliste in ihrer Reihenfolge (nach Name wie GET /shopping-list). */
            shopping: {
                name: string;
                /** @description Fehlmenge, die gekauft werden muss (bei Kästen in Flaschen). 0 bei einem vorgemerkten Produkt ohne Fehlbestand. */
                missing: number;
                /** @description Menge zum Einkaufen in unit: mit Kastengröße missing durch crate_size, aufgerundet, sonst missing. */
                quantity: number;
                /**
                 * @description crate mit Kastengröße, sonst piece.
                 * @enum {string}
                 */
                unit: "piece" | "crate";
            }[];
            /** @description true, wenn die Einkaufsliste mehr als 100 Einträge hat. */
            shopping_truncated: boolean;
        };
        SystemStatus: {
            version: string;
            /**
             * Format: int64
             * @description Bytes der Datenbankdatei stashbert.db samt WAL-Datei (stashbert.db-wal), falls es sie gibt.
             */
            database_size: number;
            /** @description Anzahl der regelmäßigen Backups stashbert-<YYYYMMDD-HHMMSS>.db in DATA_DIR/backups, ohne die Backups vor Migrationen (pre-migration-*). */
            backup_count: number;
            /**
             * Format: date-time
             * @description Zeit des neuesten regelmäßigen Backups, gelesen aus ihrem Dateinamen (UTC, auf die Sekunde), oder null ohne Backup.
             */
            last_backup_at: string | null;
            /** @description Anzahl der aufbewahrten täglichen Backups (BACKUP_KEEP). */
            backup_keep: number;
            /** @description true, wenn OFF_CONTACT gesetzt ist und unbekannte Barcodes bei Open Food Facts nachgeschlagen werden. */
            open_food_facts: boolean;
        };
        /** @description Eine Liste in Home Assistant, in die die Einkaufsliste gehen kann. */
        ShoppingTarget: {
            /** @description Undurchsichtige Kennung aus Home Assistant, z. B. todo.bring_zuhause. */
            id: string;
            /** @description Anzeigename der Liste. */
            name: string;
        };
        ShoppingTargetChoice: {
            /** @description Kennung einer gerade angebotenen Liste oder null, um die Wahl aufzuheben. */
            id: string | null;
        };
        MqttStatus: {
            /**
             * @description disabled ohne MQTT, connecting ohne Verbindung zum Broker (der Client versucht es weiter), connected mit Verbindung.
             * @enum {string}
             */
            status: "disabled" | "connecting" | "connected";
            /** @description Die zuletzt von Home Assistant angebotenen Ziellisten in ihrer Reihenfolge. Leer ohne MQTT oder ohne gültiges Angebot. */
            targets: components["schemas"]["ShoppingTarget"][];
            /** @description Die gewählte Zielliste, auch wenn sie gerade nicht angeboten wird, oder null. */
            target: components["schemas"]["ShoppingTarget"] | null;
        };
        /**
         * @description Anbieter der Produkterkennung (ADR-0021).
         * @enum {string}
         */
        RecognitionProvider: "openai" | "gemini" | "anthropic";
        /** @description Einstellungen der Produkterkennung per Foto (ADR-0021). */
        RecognitionSettings: {
            /** @description Der eingerichtete Anbieter oder null, wenn die Erkennung aus ist. */
            provider: components["schemas"]["RecognitionProvider"] | null;
            /** @description Das eingestellte Modell oder null für das Standardmodell des Anbieters. */
            model: string | null;
            /** @description true, wenn ein API-Schlüssel gespeichert ist. */
            key_set: boolean;
            /** @description Die letzten vier Zeichen des API-Schlüssels oder null ohne Schlüssel. */
            key_hint: string | null;
            /** @description Das Standardmodell je Anbieter. */
            default_models: {
                openai: string;
                gemini: string;
                anthropic: string;
            };
        };
        RecognitionSettingsUpdate: {
            /** @description Der Anbieter oder null, um die Erkennung abzuschalten. */
            provider: components["schemas"]["RecognitionProvider"] | null;
            /** @description Wird getrimmt. Fehlt es oder ist es leer, gilt das Standardmodell des Anbieters. */
            model?: string;
            /** @description Wird getrimmt. Fehlt er oder ist er leer, bleibt der gespeicherte Schlüssel, sofern der Anbieter gleich bleibt. */
            api_key?: string;
        };
        /** @description Was der Anbieter auf dem Produktfoto liest; null, wenn es nicht lesbar ist. */
        RecognitionResult: {
            /** @description Höchstens 120 Zeichen. */
            name: string | null;
            /** @description Höchstens 120 Zeichen. */
            brand: string | null;
            /** @description Menge mit Einheit, z. B. 500 g; höchstens 40 Zeichen. */
            package_size: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Der Server läuft. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alle Produkte mit ihren Barcodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Das angelegte Produkt mit seinen Barcodes. */
            201: {
                headers: {
                    /** @description Pfad des Produkts, /api/v1/products/{id}. */
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Produkt mit seinen Barcodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Produkt ist gelöscht. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatch"];
            };
        };
        responses: {
            /** @description Das geänderte Produkt mit seinen Barcodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    addBarcode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarcodeInput"];
            };
        };
        responses: {
            /** @description Der zugeordnete Barcode, normalisiert. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Barcode"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    removeBarcode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                /** @description Barcode, wird vor dem Vergleich normalisiert. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Der Barcode ist entfernt. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    mergeProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID des Produkts, das in das Zielprodukt überführt und danach gelöscht wird. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductMerge"];
            };
        };
        responses: {
            /** @description Das Zielprodukt mit seinen Barcodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Bild als JPEG, PNG oder WebP. */
            200: {
                headers: {
                    /** @description Immer private, max-age=86400. */
                    "Cache-Control": string;
                    [name: string]: unknown;
                };
                content: {
                    "image/*": unknown;
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    uploadProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/*": unknown;
            };
        };
        responses: {
            /** @description Das Produkt mit seinen Barcodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Produkt hat kein Bild mehr. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    recognizeProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Was der Anbieter auf dem Foto liest. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecognitionResult"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listMovements: {
        parameters: {
            query?: {
                /** @description Nur die Buchungen dieses Produkts. */
                product_id?: string;
                /** @description Höchstzahl der Buchungen auf der Seite. */
                limit?: number;
                /** @description next_cursor der vorigen Seite, also die id ihres letzten Eintrags. Die Seite enthält nur Buchungen mit kleinerer id. Ein Wert, der keine UUID ist, ergibt invalid_request. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eine Seite der Buchungen. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementList"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createMovement: {
        parameters: {
            query?: never;
            header?: {
                /** @description Schlüssel für Wiederholungen. Gleicher Schlüssel mit gleichem Body bucht nicht erneut, sondern liefert 201 mit der aus der gespeicherten Buchung rekonstruierten Antwort (aktuelles Produkt, product_created false, warnings leer). Gleicher Schlüssel mit anderem Body ergibt idempotency_key_mismatch. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementCreate"];
            };
        };
        responses: {
            /** @description Die angelegte Buchung mit dem geänderten Produkt. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResult"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reverseMovement: {
        parameters: {
            query?: never;
            header?: {
                /** @description Schlüssel für Wiederholungen. Gleicher Schlüssel für dieselbe Buchung storniert nicht erneut, sondern liefert 201 mit der aus der gespeicherten Stornobuchung rekonstruierten Antwort (aktuelles Produkt, product_created false, warnings leer). Gleicher Schlüssel für eine andere Anfrage ergibt idempotency_key_mismatch. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description ID der Buchung, die storniert wird. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Die Stornobuchung mit dem geänderten Produkt. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResult"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Die Produkte, bei denen etwas fehlt oder die vorgemerkt sind. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    markShoppingItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkCreate"];
            };
        };
        responses: {
            /** @description Das vorgemerkte Produkt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkResult"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    unmarkShoppingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID des Produkts, dessen Vormerkung entfernt wird. */
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Produkt ist nicht vorgemerkt. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    sendShoppingSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Der Snapshot ist angefordert. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Die Zusammenfassung. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Der Zustand. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    downloadBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Archiv. */
            200: {
                headers: {
                    /** @description attachment; filename="stashbert-<YYYYMMDD-HHMMSS>.tar.gz" mit der Zeit des Backups in UTC. */
                    "Content-Disposition": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/gzip": unknown;
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    restoreBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/gzip": unknown;
            };
        };
        responses: {
            /** @description Das Backup ist bereitgelegt; StashBert startet neu. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getMqttStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verbindung, angebotene und gewählte Zielliste. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MqttStatus"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setShoppingTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShoppingTargetChoice"];
            };
        };
        responses: {
            /** @description Verbindung, angebotene und gewählte Zielliste nach der Wahl. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MqttStatus"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRecognitionSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Die Einstellungen. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecognitionSettings"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    setRecognitionSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecognitionSettingsUpdate"];
            };
        };
        responses: {
            /** @description Die Einstellungen danach. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecognitionSettings"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
