/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status des Servers */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alle Produkte, sortiert nach Name */
        get: operations["listProducts"];
        put?: never;
        /**
         * Produkt manuell anlegen
         * @description Fehler-code: invalid_request (400), barcode_in_use (409), invalid_barcode (422).
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Ein Produkt
         * @description Fehler-code: not_found (404).
         */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        /**
         * Produkt mit Barcodes, Buchungen und Bild löschen
         * @description Fehler-code: not_found (404).
         */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /**
         * Produkt ändern (JSON Merge Patch)
         * @description Fehler-code: invalid_request (400), not_found (404).
         */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/products/{id}/barcodes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Barcode einem Produkt zuordnen
         * @description Fehler-code: invalid_request (400), not_found (404), barcode_in_use (409), invalid_barcode (422).
         */
        post: operations["addBarcode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/barcodes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                /** @description Barcode, wird vor dem Vergleich normalisiert. */
                code: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Barcode von einem Produkt entfernen
         * @description Fehler-code: not_found (404), auch bei ungültigem Barcode.
         */
        delete: operations["removeBarcode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID des Produkts, das in das Zielprodukt überführt und danach gelöscht wird. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Produkt in ein anderes Produkt überführen
         * @description Barcodes und Buchungen des Produkts id gehen auf das Zielprodukt über. Hat das Produkt id Bestand, bekommt das Ziel eine Buchung mit kind merge und delta gleich diesem Bestand; ohne Bestand bleibt das Ziel unverändert. Danach wird das Produkt id mit seinem Bild gelöscht. Die übrigen Felder des Ziels bleiben unverändert. Fehler-code: invalid_request (400, auch wenn Ziel und Quelle gleich sind), not_found (404).
         */
        post: operations["mergeProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Produktbild
         * @description Fehler-code: not_found (404), auch wenn das Produkt kein Bild hat oder die Bilddatei fehlt.
         */
        get: operations["getProductImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buchungen, neueste zuerst
         * @description Sortiert nach id absteigend, seitenweise über cursor. Ein unbekanntes product_id ergibt eine leere Liste. Fehler-code: invalid_request (400).
         */
        get: operations["listMovements"];
        put?: never;
        /**
         * Buchung anlegen
         * @description Fehler-code: invalid_request (400), not_found (404), unknown_barcode (404), stock_already_zero (409), invalid_barcode (422), idempotency_key_mismatch (422).
         */
        post: operations["createMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movements/{id}/reversal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID der Buchung, die storniert wird. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Buchung stornieren
         * @description Legt eine Buchung mit kind reversal an, die die Änderung der Buchung id zurücknimmt. Würde der Bestand negativ, wird er 0 mit der Warnung clamped_to_zero; delta ist die tatsächliche Änderung. Buchungen der Arten reversal und merge sind nicht stornierbar. Fehler-code: invalid_request (400), not_found (404), already_reversed (409), not_reversible (409), idempotency_key_mismatch (422).
         */
        post: operations["reverseMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Einkaufsliste, sortiert nach Name
         * @description Alle Produkte mit missing größer 0 oder mit Vormerkung (marked), sortiert nach Name ohne Beachtung der Groß- und Kleinschreibung.
         */
        get: operations["getShoppingList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-list/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Produkt für den Einkauf vormerken
         * @description Merkt das Produkt für den Einkauf vor (marked true), bestimmt über product_id oder barcode. Ändert nie den Bestand und legt keine Buchung an. Ein unbekannter Barcode legt das Produkt wie beim Einlagern an, aber ohne Buchung, also mit Bestand 0, und merkt es vor. Ein schon vorgemerktes Produkt bleibt unverändert. Fehler-code: invalid_request (400), not_found (404), invalid_barcode (422).
         */
        post: operations["markShoppingItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-list/items/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID des Produkts, dessen Vormerkung entfernt wird. */
                product_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Vormerkung entfernen
         * @description Setzt marked auf false. Ein Fehlbestand nach Soll bleibt auf der Einkaufsliste. Ein nicht vorgemerktes Produkt bleibt unverändert. Fehler-code: not_found (404).
         */
        delete: operations["unmarkShoppingItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Fehler nach RFC 9457 mit zusätzlichem Feld code. */
        Problem: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
            code: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        Barcode: {
            /** @description Normalisierter Barcode. */
            code: string;
            /** @description Stückzahl, die ein Scan dieses Barcodes bucht. */
            units: number;
        };
        Product: {
            id: string;
            name: string;
            brand: string | null;
            package_size: string | null;
            note: string | null;
            /** @description Bestand. Nur lesen, er ändert sich nur durch Buchungen. */
            stock: number;
            /** @description Sollbestand. */
            target: number;
            /** @description Mindestbestand. Ohne Wert gilt der Sollbestand als Schwelle. */
            min_stock: number | null;
            /** @description Fehlmenge für die Einkaufsliste. Nur lesen, wird berechnet. */
            missing: number;
            /** @description Für den Einkauf vorgemerkt. Nur lesen; eine Buchung add beendet die Vormerkung. */
            marked: boolean;
            needs_review: boolean;
            /** @enum {string} */
            origin: "openfoodfacts" | "openbeautyfacts" | "openpetfoodfacts" | "openproductsfacts" | "manual" | "placeholder";
            /** @enum {string} */
            lookup_state: "none" | "pending" | "done" | "not_found";
            has_image: boolean;
            /** @description Barcodes, sortiert nach Code. */
            barcodes: components["schemas"]["Barcode"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProductList: {
            items: components["schemas"]["Product"][];
        };
        BarcodeInput: {
            /** @description EAN-8, UPC-A, EAN-13 oder GTIN-14. Wird normalisiert gespeichert. */
            code: string;
            /**
             * @description Stückzahl, die ein Scan dieses Barcodes bucht.
             * @default 1
             */
            units?: number;
        };
        ProductCreate: {
            /** @description Wird getrimmt, danach 1 bis 120 Zeichen. */
            name: string;
            /** @description Wird getrimmt, danach höchstens 120 Zeichen. Leer wird null. */
            brand?: string;
            /** @description Wird getrimmt, danach höchstens 40 Zeichen. Leer wird null. */
            package_size?: string;
            /**
             * @description Sollbestand.
             * @default 0
             */
            target?: number;
            /** @description Mindestbestand, höchstens target. */
            min_stock?: number;
            /** @description Wird getrimmt, danach höchstens 500 Zeichen. Leer wird null. */
            note?: string;
            /** @description Barcodes des Produkts. Jeder Code darf nur einmal vorkommen. */
            barcodes?: components["schemas"]["BarcodeInput"][];
        };
        /** @description JSON Merge Patch. Ein fehlendes Feld bleibt unverändert, null löscht ein nullbares Feld. needs_review wird false, wenn der Patch name, brand oder package_size enthält. */
        ProductPatch: {
            /** @description Wird getrimmt, danach 1 bis 120 Zeichen. */
            name?: string;
            /** @description Wird getrimmt, danach höchstens 120 Zeichen. Leer wird null. */
            brand?: string | null;
            /** @description Wird getrimmt, danach höchstens 40 Zeichen. Leer wird null. */
            package_size?: string | null;
            /** @description Sollbestand. */
            target?: number;
            /** @description Mindestbestand, nach dem Ändern höchstens target. */
            min_stock?: number | null;
            /** @description Wird getrimmt, danach höchstens 500 Zeichen. Leer wird null. */
            note?: string | null;
        };
        ProductMerge: {
            /** @description ID des Zielprodukts. Muss sich von der ID der Quelle unterscheiden. */
            target_product_id: string;
        };
        /** @description Buchung für ein Produkt, bestimmt über product_id oder barcode. Genau eines der beiden Felder muss gesetzt sein, sonst invalid_request. quantity gilt für add und consume, stock ist bei inventory Pflicht und bei add und consume nicht erlaubt. */
        MovementCreate: {
            product_id?: string;
            /** @description EAN-8, UPC-A, EAN-13 oder GTIN-14, wird normalisiert. Die Menge für add und consume ist quantity × units des Barcodes; inventory ignoriert units. */
            barcode?: string;
            /** @enum {string} */
            kind: "add" | "consume" | "inventory";
            /**
             * @description Menge für add und consume.
             * @default 1
             */
            quantity?: number;
            /** @description Neuer Bestand für inventory. */
            stock?: number;
        };
        Movement: {
            id: string;
            product_id: string;
            /** @enum {string} */
            kind: "add" | "consume" | "inventory" | "reversal" | "merge";
            /** @description Tatsächliche Änderung des Bestands, darf 0 sein. */
            delta: number;
            /** @description Bestand nach der Buchung. */
            stock_after: number;
            /** @description Normalisierter Barcode, falls per Barcode gebucht wurde. */
            barcode: string | null;
            /** @description ID der stornierten Buchung, nur bei kind reversal. */
            reverses_id: string | null;
            /** Format: date-time */
            created_at: string;
        };
        MovementList: {
            /** @description Buchungen, sortiert nach id absteigend. */
            items: components["schemas"]["Movement"][];
            /** @description cursor für die nächste Seite, null auf der letzten Seite. */
            next_cursor: string | null;
        };
        MovementResult: {
            movement: components["schemas"]["Movement"];
            product: components["schemas"]["Product"];
            /** @description true, wenn das Produkt mit dieser Buchung angelegt wurde. */
            product_created: boolean;
            /** @description Hinweise zur Buchung, z. B. clamped_to_zero, wenn der Bestand auf 0 begrenzt wurde. */
            warnings: string[];
            /** @description Fertiger deutscher Anzeigetext, z. B. "Kidneybohnen 3 → 2". */
            message: string;
        };
        ShoppingItem: {
            product_id: string;
            name: string;
            brand: string | null;
            /** @description Fehlmenge, die gekauft werden muss. 0 bei einem vorgemerkten Produkt ohne Fehlbestand. */
            missing: number;
            /** @description Bestand. */
            stock: number;
            /** @description Sollbestand. */
            target: number;
            /** @description Für den Einkauf vorgemerkt. Nur lesen. */
            marked: boolean;
        };
        /** @description Vormerkung für ein Produkt, bestimmt über product_id oder barcode. Genau eines der beiden Felder muss gesetzt sein, sonst invalid_request. */
        MarkCreate: {
            product_id?: string;
            /** @description EAN-8, UPC-A, EAN-13 oder GTIN-14, wird normalisiert. */
            barcode?: string;
        };
        MarkResult: {
            product: components["schemas"]["Product"];
            /** @description true, wenn das Produkt für einen unbekannten Barcode angelegt wurde. */
            product_created: boolean;
            /** @description true, wenn das Produkt schon vorher auf der Einkaufsliste stand, wegen missing größer 0 oder marked. */
            already_listed: boolean;
            /** @description Fertiger deutscher Anzeigetext: "Vorgemerkt: <name>", "Neu vorgemerkt: <name>" oder "Schon auf der Liste: <name>". */
            message: string;
        };
        ShoppingList: {
            items: components["schemas"]["ShoppingItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Der Server läuft. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alle Produkte mit ihren Barcodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Das angelegte Produkt mit seinen Barcodes. */
            201: {
                headers: {
                    /** @description Pfad des Produkts, /api/v1/products/{id}. */
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Produkt mit seinen Barcodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Produkt ist gelöscht. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatch"];
            };
        };
        responses: {
            /** @description Das geänderte Produkt mit seinen Barcodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    addBarcode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarcodeInput"];
            };
        };
        responses: {
            /** @description Der zugeordnete Barcode, normalisiert. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Barcode"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    removeBarcode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                /** @description Barcode, wird vor dem Vergleich normalisiert. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Der Barcode ist entfernt. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    mergeProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID des Produkts, das in das Zielprodukt überführt und danach gelöscht wird. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductMerge"];
            };
        };
        responses: {
            /** @description Das Zielprodukt mit seinen Barcodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Bild als JPEG, PNG oder WebP. */
            200: {
                headers: {
                    /** @description Immer private, max-age=86400. */
                    "Cache-Control": string;
                    [name: string]: unknown;
                };
                content: {
                    "image/*": unknown;
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listMovements: {
        parameters: {
            query?: {
                /** @description Nur die Buchungen dieses Produkts. */
                product_id?: string;
                /** @description Höchstzahl der Buchungen auf der Seite. */
                limit?: number;
                /** @description next_cursor der vorigen Seite, also die id ihres letzten Eintrags. Die Seite enthält nur Buchungen mit kleinerer id. Ein Wert, der keine UUID ist, ergibt invalid_request. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eine Seite der Buchungen. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementList"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createMovement: {
        parameters: {
            query?: never;
            header?: {
                /** @description Schlüssel für Wiederholungen. Gleicher Schlüssel mit gleichem Body bucht nicht erneut, sondern liefert 201 mit der aus der gespeicherten Buchung rekonstruierten Antwort (aktuelles Produkt, product_created false, warnings leer). Gleicher Schlüssel mit anderem Body ergibt idempotency_key_mismatch. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementCreate"];
            };
        };
        responses: {
            /** @description Die angelegte Buchung mit dem geänderten Produkt. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResult"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reverseMovement: {
        parameters: {
            query?: never;
            header?: {
                /** @description Schlüssel für Wiederholungen. Gleicher Schlüssel für dieselbe Buchung storniert nicht erneut, sondern liefert 201 mit der aus der gespeicherten Stornobuchung rekonstruierten Antwort (aktuelles Produkt, product_created false, warnings leer). Gleicher Schlüssel für eine andere Anfrage ergibt idempotency_key_mismatch. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description ID der Buchung, die storniert wird. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Die Stornobuchung mit dem geänderten Produkt. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResult"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Die Produkte, bei denen etwas fehlt oder die vorgemerkt sind. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    markShoppingItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkCreate"];
            };
        };
        responses: {
            /** @description Das vorgemerkte Produkt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkResult"];
                };
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    unmarkShoppingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID des Produkts, dessen Vormerkung entfernt wird. */
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Das Produkt ist nicht vorgemerkt. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fehler nach RFC 9457. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
