//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MovementKind.
const (
	MovementKindAdd       MovementKind = "add"
	MovementKindConsume   MovementKind = "consume"
	MovementKindInventory MovementKind = "inventory"
	MovementKindMerge     MovementKind = "merge"
	MovementKindReversal  MovementKind = "reversal"
)

// Valid indicates whether the value is a known member of the MovementKind enum.
func (e MovementKind) Valid() bool {
	switch e {
	case MovementKindAdd:
		return true
	case MovementKindConsume:
		return true
	case MovementKindInventory:
		return true
	case MovementKindMerge:
		return true
	case MovementKindReversal:
		return true
	default:
		return false
	}
}

// Defines values for MovementCreateKind.
const (
	MovementCreateKindAdd       MovementCreateKind = "add"
	MovementCreateKindConsume   MovementCreateKind = "consume"
	MovementCreateKindInventory MovementCreateKind = "inventory"
)

// Valid indicates whether the value is a known member of the MovementCreateKind enum.
func (e MovementCreateKind) Valid() bool {
	switch e {
	case MovementCreateKindAdd:
		return true
	case MovementCreateKindConsume:
		return true
	case MovementCreateKindInventory:
		return true
	default:
		return false
	}
}

// Defines values for ProductLookupState.
const (
	Done     ProductLookupState = "done"
	None     ProductLookupState = "none"
	NotFound ProductLookupState = "not_found"
	Pending  ProductLookupState = "pending"
)

// Valid indicates whether the value is a known member of the ProductLookupState enum.
func (e ProductLookupState) Valid() bool {
	switch e {
	case Done:
		return true
	case None:
		return true
	case NotFound:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for ProductOrigin.
const (
	Manual            ProductOrigin = "manual"
	Openbeautyfacts   ProductOrigin = "openbeautyfacts"
	Openfoodfacts     ProductOrigin = "openfoodfacts"
	Openpetfoodfacts  ProductOrigin = "openpetfoodfacts"
	Openproductsfacts ProductOrigin = "openproductsfacts"
	Placeholder       ProductOrigin = "placeholder"
)

// Valid indicates whether the value is a known member of the ProductOrigin enum.
func (e ProductOrigin) Valid() bool {
	switch e {
	case Manual:
		return true
	case Openbeautyfacts:
		return true
	case Openfoodfacts:
		return true
	case Openpetfoodfacts:
		return true
	case Openproductsfacts:
		return true
	case Placeholder:
		return true
	default:
		return false
	}
}

// Barcode defines model for Barcode.
type Barcode struct {
	// Code Normalisierter Barcode.
	Code string `json:"code"`

	// Units Stückzahl, die ein Scan dieses Barcodes bucht.
	Units int `json:"units"`
}

// BarcodeInput defines model for BarcodeInput.
type BarcodeInput struct {
	// Code EAN-8, UPC-A, EAN-13 oder GTIN-14. Wird normalisiert gespeichert.
	Code string `json:"code"`

	// Units Stückzahl, die ein Scan dieses Barcodes bucht.
	Units *int `json:"units,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Movement defines model for Movement.
type Movement struct {
	// Barcode Normalisierter Barcode, falls per Barcode gebucht wurde.
	Barcode   nullable.Nullable[string] `json:"barcode"`
	CreatedAt time.Time                 `json:"created_at"`

	// Delta Tatsächliche Änderung des Bestands, darf 0 sein.
	Delta     int          `json:"delta"`
	Id        string       `json:"id"`
	Kind      MovementKind `json:"kind"`
	ProductId string       `json:"product_id"`

	// ReversesId ID der stornierten Buchung, nur bei kind reversal.
	ReversesId nullable.Nullable[string] `json:"reverses_id"`

	// StockAfter Bestand nach der Buchung.
	StockAfter int `json:"stock_after"`
}

// MovementKind defines model for Movement.Kind.
type MovementKind string

// MovementCreate Buchung für ein Produkt, bestimmt über product_id oder barcode. Genau eines der beiden Felder muss gesetzt sein, sonst invalid_request. quantity gilt für add und consume, stock ist bei inventory Pflicht und bei add und consume nicht erlaubt.
type MovementCreate struct {
	// Barcode EAN-8, UPC-A, EAN-13 oder GTIN-14, wird normalisiert. Die Menge für add und consume ist quantity × units des Barcodes; inventory ignoriert units.
	Barcode   *string            `json:"barcode,omitempty"`
	Kind      MovementCreateKind `json:"kind"`
	ProductId *string            `json:"product_id,omitempty"`

	// Quantity Menge für add und consume.
	Quantity *int `json:"quantity,omitempty"`

	// Stock Neuer Bestand für inventory.
	Stock *int `json:"stock,omitempty"`
}

// MovementCreateKind defines model for MovementCreate.Kind.
type MovementCreateKind string

// MovementResult defines model for MovementResult.
type MovementResult struct {
	// Message Fertiger deutscher Anzeigetext, z. B. "Kidneybohnen 3 → 2".
	Message  string   `json:"message"`
	Movement Movement `json:"movement"`
	Product  Product  `json:"product"`

	// ProductCreated true, wenn das Produkt mit dieser Buchung angelegt wurde.
	ProductCreated bool `json:"product_created"`

	// Warnings Hinweise zur Buchung, z. B. clamped_to_zero, wenn der Bestand auf 0 begrenzt wurde.
	Warnings []string `json:"warnings"`
}

// Problem Fehler nach RFC 9457 mit zusätzlichem Feld code.
type Problem struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Status int     `json:"status"`
	Title  string  `json:"title"`
	Type   *string `json:"type,omitempty"`
}

// Product defines model for Product.
type Product struct {
	// Barcodes Barcodes, sortiert nach Code.
	Barcodes    []Barcode                 `json:"barcodes"`
	Brand       nullable.Nullable[string] `json:"brand"`
	CreatedAt   time.Time                 `json:"created_at"`
	HasImage    bool                      `json:"has_image"`
	Id          string                    `json:"id"`
	LookupState ProductLookupState        `json:"lookup_state"`

	// MinStock Mindestbestand. Ohne Wert gilt der Sollbestand als Schwelle.
	MinStock nullable.Nullable[int] `json:"min_stock"`

	// Missing Fehlmenge für die Einkaufsliste. Nur lesen, wird berechnet.
	Missing     int                       `json:"missing"`
	Name        string                    `json:"name"`
	NeedsReview bool                      `json:"needs_review"`
	Note        nullable.Nullable[string] `json:"note"`
	Origin      ProductOrigin             `json:"origin"`
	PackageSize nullable.Nullable[string] `json:"package_size"`

	// Stock Bestand. Nur lesen, er ändert sich nur durch Buchungen.
	Stock int `json:"stock"`

	// Target Sollbestand.
	Target    int       `json:"target"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ProductLookupState defines model for Product.LookupState.
type ProductLookupState string

// ProductOrigin defines model for Product.Origin.
type ProductOrigin string

// ProductCreate defines model for ProductCreate.
type ProductCreate struct {
	// Barcodes Barcodes des Produkts. Jeder Code darf nur einmal vorkommen.
	Barcodes *[]BarcodeInput `json:"barcodes,omitempty"`

	// Brand Wird getrimmt, danach höchstens 120 Zeichen. Leer wird null.
	Brand *string `json:"brand,omitempty"`

	// MinStock Mindestbestand, höchstens target.
	MinStock *int `json:"min_stock,omitempty"`

	// Name Wird getrimmt, danach 1 bis 120 Zeichen.
	Name string `json:"name"`

	// Note Wird getrimmt, danach höchstens 500 Zeichen. Leer wird null.
	Note *string `json:"note,omitempty"`

	// PackageSize Wird getrimmt, danach höchstens 40 Zeichen. Leer wird null.
	PackageSize *string `json:"package_size,omitempty"`

	// Target Sollbestand.
	Target *int `json:"target,omitempty"`
}

// ProductList defines model for ProductList.
type ProductList struct {
	Items []Product `json:"items"`
}

// ProductPatch JSON Merge Patch. Ein fehlendes Feld bleibt unverändert, null löscht ein nullbares Feld. needs_review wird false, wenn der Patch name, brand oder package_size enthält.
type ProductPatch struct {
	// Brand Wird getrimmt, danach höchstens 120 Zeichen. Leer wird null.
	Brand nullable.Nullable[string] `json:"brand,omitempty"`

	// MinStock Mindestbestand, nach dem Ändern höchstens target.
	MinStock nullable.Nullable[int] `json:"min_stock,omitempty"`

	// Name Wird getrimmt, danach 1 bis 120 Zeichen.
	Name *string `json:"name,omitempty"`

	// Note Wird getrimmt, danach höchstens 500 Zeichen. Leer wird null.
	Note nullable.Nullable[string] `json:"note,omitempty"`

	// PackageSize Wird getrimmt, danach höchstens 40 Zeichen. Leer wird null.
	PackageSize nullable.Nullable[string] `json:"package_size,omitempty"`

	// Target Sollbestand.
	Target *int `json:"target,omitempty"`
}

// CreateMovementParams defines parameters for CreateMovement.
type CreateMovementParams struct {
	// IdempotencyKey Schlüssel für Wiederholungen. Gleicher Schlüssel mit gleichem Body bucht nicht erneut, sondern liefert 201 mit der aus der gespeicherten Buchung rekonstruierten Antwort (aktuelles Produkt, product_created false, warnings leer). Gleicher Schlüssel mit anderem Body ergibt idempotency_key_mismatch.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// CreateMovementJSONRequestBody defines body for CreateMovement for application/json ContentType.
type CreateMovementJSONRequestBody = MovementCreate

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = ProductCreate

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = ProductPatch

// AddBarcodeJSONRequestBody defines body for AddBarcode for application/json ContentType.
type AddBarcodeJSONRequestBody = BarcodeInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Status des Servers
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// CreateMovement Buchung anlegen
	// (POST /movements)
	CreateMovement(w http.ResponseWriter, r *http.Request, params CreateMovementParams)
	// ListProducts Alle Produkte, sortiert nach Name
	// (GET /products)
	ListProducts(w http.ResponseWriter, r *http.Request)
	// CreateProduct Produkt manuell anlegen
	// (POST /products)
	CreateProduct(w http.ResponseWriter, r *http.Request)
	// DeleteProduct Produkt mit Barcodes und Buchungen löschen
	// (DELETE /products/{id})
	DeleteProduct(w http.ResponseWriter, r *http.Request, id string)
	// GetProduct Ein Produkt
	// (GET /products/{id})
	GetProduct(w http.ResponseWriter, r *http.Request, id string)
	// UpdateProduct Produkt ändern (JSON Merge Patch)
	// (PATCH /products/{id})
	UpdateProduct(w http.ResponseWriter, r *http.Request, id string)
	// AddBarcode Barcode einem Produkt zuordnen
	// (POST /products/{id}/barcodes)
	AddBarcode(w http.ResponseWriter, r *http.Request, id string)
	// RemoveBarcode Barcode von einem Produkt entfernen
	// (DELETE /products/{id}/barcodes/{code})
	RemoveBarcode(w http.ResponseWriter, r *http.Request, id string, code string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMovement operation middleware
func (siw *ServerInterfaceWrapper) CreateMovement(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateMovementParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMovement(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProducts operation middleware
func (siw *ServerInterfaceWrapper) ListProducts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProduct(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProduct operation middleware
func (siw *ServerInterfaceWrapper) DeleteProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProduct(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProduct(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProduct(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddBarcode operation middleware
func (siw *ServerInterfaceWrapper) AddBarcode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddBarcode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveBarcode operation middleware
func (siw *ServerInterfaceWrapper) RemoveBarcode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", r.PathValue("code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveBarcode(w, r, id, code)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/products", wrapper.ListProducts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/products", wrapper.CreateProduct)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/products/{id}", wrapper.DeleteProduct)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/products/{id}", wrapper.GetProduct)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/products/{id}", wrapper.UpdateProduct)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/products/{id}/barcodes", wrapper.AddBarcode)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/products/{id}/barcodes/{code}", wrapper.RemoveBarcode)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/movements", wrapper.CreateMovement)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetHealthdefaultApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovementRequestObject struct {
	Params CreateMovementParams
	Body   *CreateMovementJSONRequestBody
}

type CreateMovementResponseObject interface {
	VisitCreateMovementResponse(w http.ResponseWriter) error
}

type CreateMovement201JSONResponse MovementResult

func (response CreateMovement201JSONResponse) VisitCreateMovementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMovementdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateMovementdefaultApplicationProblemPlusJSONResponse) VisitCreateMovementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListProductsRequestObject struct {
}

type ListProductsResponseObject interface {
	VisitListProductsResponse(w http.ResponseWriter) error
}

type ListProducts200JSONResponse ProductList

func (response ListProducts200JSONResponse) VisitListProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProductsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListProductsdefaultApplicationProblemPlusJSONResponse) VisitListProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProductRequestObject struct {
	Body *CreateProductJSONRequestBody
}

type CreateProductResponseObject interface {
	VisitCreateProductResponse(w http.ResponseWriter) error
}

type CreateProduct201ResponseHeaders struct {
	Location string
}

type CreateProduct201JSONResponse struct {
	Body    Product
	Headers CreateProduct201ResponseHeaders
}

func (response CreateProduct201JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProductdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateProductdefaultApplicationProblemPlusJSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteProductRequestObject struct {
	Id string `json:"id"`
}

type DeleteProductResponseObject interface {
	VisitDeleteProductResponse(w http.ResponseWriter) error
}

type DeleteProduct204Response struct {
}

func (response DeleteProduct204Response) VisitDeleteProductResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProductdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteProductdefaultApplicationProblemPlusJSONResponse) VisitDeleteProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProductRequestObject struct {
	Id string `json:"id"`
}

type GetProductResponseObject interface {
	VisitGetProductResponse(w http.ResponseWriter) error
}

type GetProduct200JSONResponse Product

func (response GetProduct200JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProductdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetProductdefaultApplicationProblemPlusJSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProductRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateProductJSONRequestBody
}

type UpdateProductResponseObject interface {
	VisitUpdateProductResponse(w http.ResponseWriter) error
}

type UpdateProduct200JSONResponse Product

func (response UpdateProduct200JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProductdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateProductdefaultApplicationProblemPlusJSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AddBarcodeRequestObject struct {
	Id   string `json:"id"`
	Body *AddBarcodeJSONRequestBody
}

type AddBarcodeResponseObject interface {
	VisitAddBarcodeResponse(w http.ResponseWriter) error
}

type AddBarcode201JSONResponse Barcode

func (response AddBarcode201JSONResponse) VisitAddBarcodeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AddBarcodedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response AddBarcodedefaultApplicationProblemPlusJSONResponse) VisitAddBarcodeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveBarcodeRequestObject struct {
	Id   string `json:"id"`
	Code string `json:"code"`
}

type RemoveBarcodeResponseObject interface {
	VisitRemoveBarcodeResponse(w http.ResponseWriter) error
}

type RemoveBarcode204Response struct {
}

func (response RemoveBarcode204Response) VisitRemoveBarcodeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveBarcodedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response RemoveBarcodedefaultApplicationProblemPlusJSONResponse) VisitRemoveBarcodeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Status des Servers
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// CreateMovement Buchung anlegen
	// (POST /movements)
	CreateMovement(ctx context.Context, request CreateMovementRequestObject) (CreateMovementResponseObject, error)
	// ListProducts Alle Produkte, sortiert nach Name
	// (GET /products)
	ListProducts(ctx context.Context, request ListProductsRequestObject) (ListProductsResponseObject, error)
	// CreateProduct Produkt manuell anlegen
	// (POST /products)
	CreateProduct(ctx context.Context, request CreateProductRequestObject) (CreateProductResponseObject, error)
	// DeleteProduct Produkt mit Barcodes und Buchungen löschen
	// (DELETE /products/{id})
	DeleteProduct(ctx context.Context, request DeleteProductRequestObject) (DeleteProductResponseObject, error)
	// GetProduct Ein Produkt
	// (GET /products/{id})
	GetProduct(ctx context.Context, request GetProductRequestObject) (GetProductResponseObject, error)
	// UpdateProduct Produkt ändern (JSON Merge Patch)
	// (PATCH /products/{id})
	UpdateProduct(ctx context.Context, request UpdateProductRequestObject) (UpdateProductResponseObject, error)
	// AddBarcode Barcode einem Produkt zuordnen
	// (POST /products/{id}/barcodes)
	AddBarcode(ctx context.Context, request AddBarcodeRequestObject) (AddBarcodeResponseObject, error)
	// RemoveBarcode Barcode von einem Produkt entfernen
	// (DELETE /products/{id}/barcodes/{code})
	RemoveBarcode(ctx context.Context, request RemoveBarcodeRequestObject) (RemoveBarcodeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMovement operation middleware
func (sh *strictHandler) CreateMovement(w http.ResponseWriter, r *http.Request, params CreateMovementParams) {
	var request CreateMovementRequestObject

	request.Params = params

	var body CreateMovementJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMovement(ctx, request.(CreateMovementRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMovement")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateMovementResponseObject); ok {
		if err := validResponse.VisitCreateMovementResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProducts operation middleware
func (sh *strictHandler) ListProducts(w http.ResponseWriter, r *http.Request) {
	var request ListProductsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProducts(ctx, request.(ListProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProducts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProductsResponseObject); ok {
		if err := validResponse.VisitListProductsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProduct operation middleware
func (sh *strictHandler) CreateProduct(w http.ResponseWriter, r *http.Request) {
	var request CreateProductRequestObject

	var body CreateProductJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProduct(ctx, request.(CreateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProductResponseObject); ok {
		if err := validResponse.VisitCreateProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProduct operation middleware
func (sh *strictHandler) DeleteProduct(w http.ResponseWriter, r *http.Request, id string) {
	var request DeleteProductRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProduct(ctx, request.(DeleteProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProductResponseObject); ok {
		if err := validResponse.VisitDeleteProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProduct operation middleware
func (sh *strictHandler) GetProduct(w http.ResponseWriter, r *http.Request, id string) {
	var request GetProductRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProduct(ctx, request.(GetProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProductResponseObject); ok {
		if err := validResponse.VisitGetProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProduct operation middleware
func (sh *strictHandler) UpdateProduct(w http.ResponseWriter, r *http.Request, id string) {
	var request UpdateProductRequestObject

	request.Id = id

	var body UpdateProductJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProduct(ctx, request.(UpdateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateProductResponseObject); ok {
		if err := validResponse.VisitUpdateProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddBarcode operation middleware
func (sh *strictHandler) AddBarcode(w http.ResponseWriter, r *http.Request, id string) {
	var request AddBarcodeRequestObject

	request.Id = id

	var body AddBarcodeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddBarcode(ctx, request.(AddBarcodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddBarcode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddBarcodeResponseObject); ok {
		if err := validResponse.VisitAddBarcodeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveBarcode operation middleware
func (sh *strictHandler) RemoveBarcode(w http.ResponseWriter, r *http.Request, id string, code string) {
	var request RemoveBarcodeRequestObject

	request.Id = id
	request.Code = code

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveBarcode(ctx, request.(RemoveBarcodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveBarcode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RemoveBarcodeResponseObject); ok {
		if err := validResponse.VisitRemoveBarcodeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FrLchvHFf2VW50srMoIBGmpEiMrUrJl2ZLMsuy4KrIK1Zi5mGmjp3vcD9KkCrtUPiCb/IC+wSvt8Cf5",
	"klQ/5gGgARJ6lbwiMa++j3NPn3tnXpFc1o0UKIwmk1dE5xXW1P97RlUuC3T/Nko2qAxDf6I9WqDOFWsM",
	"k4JMyDOpasqZZqgMKoh3j0hGzFWDZEK0UUyUZJkRK5jR2094blZv8sU1rXgGBUNAJuB5ToX7oVG3j9Qw",
	"s3llBk9mwmCJiiyXGVH4q2UKCzJ5EQxtl3vZXS5nv2BunCHxiY9FY81t/fzy9Nndv2Xw4/mDu6cZuF/H",
	"n4MsUMGjHx4/u3t8bwQ/MVWAGMQDStQNsrxCZW6KyJxabsjkOHvn6NT0N1bbmkyOx+NxRmom4s/bBS4V",
	"sK+RclNth0obaqz/D4Vb4gWRC/Iy4egFKu39ebV5bsOE+MT+jpQ5T+UF1igSuZv14L0NTDOYU841NP0h",
	"KNFHEi6tGuL4RWtxRoTlnLxcZiRXSA0WU+otmbslDJmQghq8a1iNqZQXyA3dtu8HavTqdV5xhxZY/UsU",
	"qKwowWX2DLWhotAZFFTNYQwamUjVQUZYkQhxRhZMFMMs0aIgGcml0NZbycQFCiPVFXHZcKGn3CEJVYnJ",
	"fDZKFjY30x3rhWegjufXXX38EFzZaCOV8OkQcGbzyooyA2EVzJCBMxhaS/YnQRuZL6Z0blBtrxVDB4Lm",
	"lV81rnQLFmEFWfMzRrHN4PrCWYe8defXMLIPyg/8ZQkHgr0wX71RvvbPnUULk8EMtWF1bWD1ZoYKeksD",
	"K0V7RvAIBbXuVtQ+AjNkBQr4Crn7VVutHU2huTYeVxloKbQBJi4oZ8XUhQS1GcGvlgrDzBWUjJtgDy0K",
	"sKKACKQMfEiAaeOT2KEKzucO18Zf7M5s3AjCn0XFqZ15DrtlVd9IyhlcbpLyCB4yhKcoSkx64c3vnF39",
	"FzxJh0KMXPv3gWusFFJ5svfXJWn+9uX3FrXWmrp/G9nt74FbRsR9gmHRuvqKBedX6vzaWmNtlfGNtegD",
	"uK98vkdteWI/qFFrWiaQ85W7pkQFBVrj1I+CU3GNrESDv5kMrkdwNoKfybesEHg1k5VAAZ/D//79Hzj5",
	"mSSzXA92pT8rnJMJ+dNRL7OOosY6am0e5PamW87jZQM0RF7Z9swoixlcohBQUN3yBdTMBMnQcSBQUSLH",
	"cmurIzMpOVLhlrukSjBRJmTb10xcItMI11b1BB7ilnNaN1hMjZxeo5KtOQN8UOs2shmWCsX1wAJmsNZJ",
	"nMcDVCl6tQWQLvZ9SLdDNfAm65CRQtW5kjOOdQo1FUcVdpPvv3oAX9y7/1cf2WurV6/Ntd+9a8+t0Mrg",
	"tLhM6AJDGU+e6lXWdjEaZjjuiddNeivcn/W6a6cGPO+hmmTnBERavnR7irtcmRC6B3Ij2fuwHx+yDYGM",
	"zBQVA1J8XxKtonrK6kgb2yWxg4e5lAvbTF0gcUj2Qgq3SoOiCLYV4YCQZjqXdo3Y+qfVTEx3EO1TJgrU",
	"ZhYqaQTfVQLhJ99uuJ3ZVdlzyfmsrTSu4XleXSLna3K2BdEgWDXT2q2fxH3d7yCuD/mSiQW1c82ZNjiC",
	"Z1YBR40i7rgzVJhXAk1apwpap1ErEAs9VXjB8DIdfiEN7s+5VKxkYq0raVDMpSzmNDcO5O73DKk1V8Mj",
	"DZrNiyKF6PZYTYX10rjhNMdKOg2V3rRpvqAlTjW7vsHaHVk+a9M7iCwqWL0WhUu1Znnl1XJhVV61/Is7",
	"2gJDVYkm0Xr3OEnfaJviwPJJqWif7bZcN2ITE9rGobN1WAI9MjcA0uV6o/yGNZz1BLVGB2vO7SG8Xpkf",
	"SnteM8b9V4/gG3Sl6bgv9HEue8hETTlcSLWQdY3iUFYMI4x91Lhumh9RlGiU6xxcP+n5uFr9nlfaoNBw",
	"fDKGf/qRhRjBE0QVBbTlPC16bstT2XCVkOODVWHPG7fx6hhmbN2hlAMtnRwYp/vjw+K0yQcHLnfvsNWG",
	"9R47gnG2v/bfRZ77rOwpoSdMJ3RDh/NbAX4ggfcqwfCwPcacU5NX2yn45vl3z+ApqhLBXzFyOxzMneBz",
	"MA6absaRzVynd4EqMnHmswB89bv2PSwT/sCMqnjTCIaUFRI3p1zjQBX7FcGFMQNfuaGJHYIGUJhq9Zqn",
	"2uMPWeupLeuAoo+DlzqOtMRbs0BSsPyx6CAVyo/AC6llbykIDiWFjZpzh5iYS7dObFTIc0N1dYbKwOn5",
	"48Gcd0LGo+PRmCyD8KINIxPyuT/komQqD/WjqptER/tdIVBn/eOCTMgjNHFWnRGFupFChxo5GY9D+yVM",
	"bNFp03CW+1uPftFhNh3I5iYqiit499bD99Bpb1QXqICvXtu5GYXWLnLwzvWb0HD+5TA72jY1YUiqUR35",
	"FGlb11RdhUwYG0RKsFn7C47aXtrHrZHa7OqD7zoFMtmcFMJn98bjOxl0/Y07cO9OBlYshLwU0yic2sNx",
	"jMoV0uLKjwvcmS/uZN2D+xtOTtzhAutGGhT51XSBV9Oa6drzpz8/ItkGJoKAezqYEFBFazTO4cmLrQrI",
	"K756ozXy0Ov8xLBAVUke5DU84uGFDgwudBOAMhyv4UwWV+FlTDfWFGiNn6t6BuQM5w7/J+Njf6djemrD",
	"cHbwwqgfi4PChRTaKBvH5afCXEpl4DO6MNb1dbofC28MPbqtJk4+gCOqO7vdoM7G1gtUpdvudgXci1UX",
	"swppEYjZ8zF53N9w91u8ItkA0DX97QmK0tXwyf37nlHa38fbzcTLsLmjNs6g91bBG1P35bqIMMricos/",
	"jt/76nFomeIRht10DjsYBLDUUGLUHti9DviUeaYfN3IsUQSSaRvrnUzuNON5e9EHJPOhRE04eMo5tkFG",
	"nwFWKVeascf7lAO/ZvvmDO6ZK9Vl9g4EH2l5ysTUatxL2rtI+byb1X6IKl9v4D9ykXf9SqK6qR5U93BA",
	"r5GJNXBlkVu9eU9ksGQ7XedzWqxNGzI4og07ujjuCu3oFSuWI7IZgiE1b5Lv8tOFdhc0KtwGmOYW73II",
	"FkeDN6B8Q69sQ/ahf8oQsmvQubf9/IeD9y/urWKJsU38lFljiMdukuXC0s0YY7OLfhybbCMOC+wjNDuj",
	"Ov5YBbm3DD/dbH3ZfxJAllvS1qsz1zz12owVB3HAS/fM5MDkLXqA7dT/6EewH2UbCHOfW+0CHw10vZL7",
	"o+KvNTv4IeCzzTnanQQnHw1n5x8Esu+va30nlXNaFGeD74LeP7bXXwN8XIXTvZhNz0GubYlSFQJdB9N+",
	"brf2Ic6n3LPEvCITWHe1eW29Q2IfpI9euT9vLTsyoDav/EdSVpSrN9yw0rXj/We16wj7Ht24ZgiyG0XJ",
	"4FtHJ0pQmDkq8YdIx4UUGymJ1gct8t6pJNvxai++5L6Qyjfk/0AVxj8b+M5SJgzY4JZ85mMRJ3TOL6s4",
	"mZAo8Mny5fL/AwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
