//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ProductLookupState.
const (
	Done     ProductLookupState = "done"
	None     ProductLookupState = "none"
	NotFound ProductLookupState = "not_found"
	Pending  ProductLookupState = "pending"
)

// Valid indicates whether the value is a known member of the ProductLookupState enum.
func (e ProductLookupState) Valid() bool {
	switch e {
	case Done:
		return true
	case None:
		return true
	case NotFound:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for ProductOrigin.
const (
	Manual            ProductOrigin = "manual"
	Openbeautyfacts   ProductOrigin = "openbeautyfacts"
	Openfoodfacts     ProductOrigin = "openfoodfacts"
	Openpetfoodfacts  ProductOrigin = "openpetfoodfacts"
	Openproductsfacts ProductOrigin = "openproductsfacts"
	Placeholder       ProductOrigin = "placeholder"
)

// Valid indicates whether the value is a known member of the ProductOrigin enum.
func (e ProductOrigin) Valid() bool {
	switch e {
	case Manual:
		return true
	case Openbeautyfacts:
		return true
	case Openfoodfacts:
		return true
	case Openpetfoodfacts:
		return true
	case Openproductsfacts:
		return true
	case Placeholder:
		return true
	default:
		return false
	}
}

// Barcode defines model for Barcode.
type Barcode struct {
	// Code Normalisierter Barcode.
	Code string `json:"code"`

	// Units Stückzahl, die ein Scan dieses Barcodes bucht.
	Units int `json:"units"`
}

// BarcodeInput defines model for BarcodeInput.
type BarcodeInput struct {
	// Code EAN-8, UPC-A, EAN-13 oder GTIN-14. Wird normalisiert gespeichert.
	Code string `json:"code"`

	// Units Stückzahl, die ein Scan dieses Barcodes bucht.
	Units *int `json:"units,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Problem Fehler nach RFC 9457 mit zusätzlichem Feld code.
type Problem struct {
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Status int     `json:"status"`
	Title  string  `json:"title"`
	Type   *string `json:"type,omitempty"`
}

// Product defines model for Product.
type Product struct {
	// Barcodes Barcodes, sortiert nach Code.
	Barcodes    []Barcode                 `json:"barcodes"`
	Brand       nullable.Nullable[string] `json:"brand"`
	CreatedAt   time.Time                 `json:"created_at"`
	HasImage    bool                      `json:"has_image"`
	Id          string                    `json:"id"`
	LookupState ProductLookupState        `json:"lookup_state"`

	// MinStock Mindestbestand. Ohne Wert gilt der Sollbestand als Schwelle.
	MinStock nullable.Nullable[int] `json:"min_stock"`

	// Missing Fehlmenge für die Einkaufsliste. Nur lesen, wird berechnet.
	Missing     int                       `json:"missing"`
	Name        string                    `json:"name"`
	NeedsReview bool                      `json:"needs_review"`
	Note        nullable.Nullable[string] `json:"note"`
	Origin      ProductOrigin             `json:"origin"`
	PackageSize nullable.Nullable[string] `json:"package_size"`

	// Stock Bestand. Nur lesen, er ändert sich nur durch Buchungen.
	Stock int `json:"stock"`

	// Target Sollbestand.
	Target    int       `json:"target"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ProductLookupState defines model for Product.LookupState.
type ProductLookupState string

// ProductOrigin defines model for Product.Origin.
type ProductOrigin string

// ProductCreate defines model for ProductCreate.
type ProductCreate struct {
	// Barcodes Barcodes des Produkts. Jeder Code darf nur einmal vorkommen.
	Barcodes *[]BarcodeInput `json:"barcodes,omitempty"`

	// Brand Wird getrimmt, danach höchstens 120 Zeichen. Leer wird null.
	Brand *string `json:"brand,omitempty"`

	// MinStock Mindestbestand, höchstens target.
	MinStock *int `json:"min_stock,omitempty"`

	// Name Wird getrimmt, danach 1 bis 120 Zeichen.
	Name string `json:"name"`

	// Note Wird getrimmt, danach höchstens 500 Zeichen. Leer wird null.
	Note *string `json:"note,omitempty"`

	// PackageSize Wird getrimmt, danach höchstens 40 Zeichen. Leer wird null.
	PackageSize *string `json:"package_size,omitempty"`

	// Target Sollbestand.
	Target *int `json:"target,omitempty"`
}

// ProductList defines model for ProductList.
type ProductList struct {
	Items []Product `json:"items"`
}

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = ProductCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Status des Servers
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ListProducts Alle Produkte, sortiert nach Name
	// (GET /products)
	ListProducts(w http.ResponseWriter, r *http.Request)
	// CreateProduct Produkt manuell anlegen
	// (POST /products)
	CreateProduct(w http.ResponseWriter, r *http.Request)
	// GetProduct Ein Produkt
	// (GET /products/{id})
	GetProduct(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProducts operation middleware
func (siw *ServerInterfaceWrapper) ListProducts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProduct(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProduct(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/products", wrapper.ListProducts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/products", wrapper.CreateProduct)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/products/{id}", wrapper.GetProduct)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetHealthdefaultApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListProductsRequestObject struct {
}

type ListProductsResponseObject interface {
	VisitListProductsResponse(w http.ResponseWriter) error
}

type ListProducts200JSONResponse ProductList

func (response ListProducts200JSONResponse) VisitListProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProductsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListProductsdefaultApplicationProblemPlusJSONResponse) VisitListProductsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProductRequestObject struct {
	Body *CreateProductJSONRequestBody
}

type CreateProductResponseObject interface {
	VisitCreateProductResponse(w http.ResponseWriter) error
}

type CreateProduct201ResponseHeaders struct {
	Location string
}

type CreateProduct201JSONResponse struct {
	Body    Product
	Headers CreateProduct201ResponseHeaders
}

func (response CreateProduct201JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProductdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateProductdefaultApplicationProblemPlusJSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProductRequestObject struct {
	Id string `json:"id"`
}

type GetProductResponseObject interface {
	VisitGetProductResponse(w http.ResponseWriter) error
}

type GetProduct200JSONResponse Product

func (response GetProduct200JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProductdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetProductdefaultApplicationProblemPlusJSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Status des Servers
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ListProducts Alle Produkte, sortiert nach Name
	// (GET /products)
	ListProducts(ctx context.Context, request ListProductsRequestObject) (ListProductsResponseObject, error)
	// CreateProduct Produkt manuell anlegen
	// (POST /products)
	CreateProduct(ctx context.Context, request CreateProductRequestObject) (CreateProductResponseObject, error)
	// GetProduct Ein Produkt
	// (GET /products/{id})
	GetProduct(ctx context.Context, request GetProductRequestObject) (GetProductResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProducts operation middleware
func (sh *strictHandler) ListProducts(w http.ResponseWriter, r *http.Request) {
	var request ListProductsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProducts(ctx, request.(ListProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProducts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProductsResponseObject); ok {
		if err := validResponse.VisitListProductsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProduct operation middleware
func (sh *strictHandler) CreateProduct(w http.ResponseWriter, r *http.Request) {
	var request CreateProductRequestObject

	var body CreateProductJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProduct(ctx, request.(CreateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProductResponseObject); ok {
		if err := validResponse.VisitCreateProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProduct operation middleware
func (sh *strictHandler) GetProduct(w http.ResponseWriter, r *http.Request, id string) {
	var request GetProductRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProduct(ctx, request.(GetProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProductResponseObject); ok {
		if err := validResponse.VisitGetProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFffbtu2F34Vgr/fRYsp/pOm2Oq7JGu7DF0WLBsKLAgMWjyWWFOHGnmYIgn8Nn2GXfUuLzaQkmxZVpxk",
	"a4FeGLAo8vz5znc+Ht3y1BSlQUByfHLLXZpDIeLfI2FTIyH8La0pwZKC+KJZleBSq0pSBvmEnxpbCK2c",
	"AktgWX16wBNO1yXwCXdkFWZ8mXCPity2hXO6+5wubkSuEyYVMFDIzlOB4cGBa0w6NvNpTi3LCgkysHy5",
	"TLiFv7yyIPnkogq0cXe52m5mHyClEEht8QRLT4/N8/Xh6d4PCfvj7HjvMGHhafyCGQmWvf395HRvfDBg",
	"75WVDFt4sAxcCSrNwdJDiMyF18Qn4+Q/o1MoVIUvoq3HINWH0E8gNOXb2DgS5OM/wODigpsFv+zJ7Aqs",
	"iwncdt91Qqgtrk/0hXNmzUxDsV2VN5BrsAxFmrPf3hyzVwcvv2eFInbj3d0nutEB/IK9AS1Zw8v+am9l",
	"IIGE0r2v1ih08U04KdL9BquFh/CozidrXO6t0Zk10qc9BJ7VlNiGqyFLwpwJ2y1V0B3X0CiCIh77v4U5",
	"n/D/DdcyMaw1YlgbWafEhbXiOjzPrEC5zvGiSTLh6LXml8uEpxYEgZyKGPg8dAvxCZeCYI9UAX1tkgs3",
	"VYXI2vDNjNEgMLxWshdvbczCl9MAJLQZiwaDlxJQVrHJagENTefGo+wldKFw6siki21Uf1EowdEMHAmU",
	"A/ZrjsDex/5XmljQiHOjdf2eCe3YeZp/BK1bOnmxIlELrEI5F/z38r4AzIDN7z7bKAyvFS6EnzutHMGA",
	"nXrLNDjAhH0MujQDC2mO0CugCUdR9LMWAaSbWrhS8LEffjQEu2turMoUbqhGCTg3Rs5FSo4n8XkGwtN1",
	"e6UE6m4qK9K7Zq0Q6IUO5dQihdxoCba3fqVIFyKDqVM3D0R7T5WPmvK2kAXL7j6hDKV2Ks0Zesukt2nO",
	"jnyae8wA++EmYTOgnrtwzZP+g76UT2yfjr4oyetqN+3awaYuaIPDKtZ2C6yZ2SHIqtad9mv3cLIWqA05",
	"2Ehuh+AdxyP/RvZY+EUrC3ID9jOE1gzax6Sw81g9UFgIza6MXZiiAHyqKlYzxS5p3AwtzgwZkFVFQQmT",
	"Iupxfvd3mjsCdGy8P2J/xhkCB+wdgK3aObC1d6R4tE4lbS9VjTemh9EumXhMEmM2U5vx98XbqMcTYXk5",
	"ehos3fZ/oruDp3lrt3c92I2S3a2+C/dOC8ci7GiQd8r1TAUrFj+KzrWpbSZ35SQa2w4m7FM4N8FPPRLx",
	"cxIuPwpieXh20pr4Jnw0GA9GfFlJvCgVn/AXcSkUjvIY7TBfzaQ1tiE7EdA8kXzC3wLVU2uI0JUGXZX4",
	"/mhUDXpIgPGgKEut0nh0+MFVU2qV+EOw1B5iepvl/DHc8mCvwDJ998nPaVANkXX57/VfVqPtd0+LoxmI",
	"ewLpG4kHsW7OF4Ww11UlyFdyWMXs4oZhc7veC3Kg1lmz6Svi3GZyT46HWkMj5BDnfZVbwNXH0LeM/Ubs",
	"3UH8NLR2kCvj6L6vnb2Q4oQpvBJayWnoRnDEnh2MRs8TVt+CU4VT7yCsvnqerDbXb9mzg/395wOedMpb",
	"Xa1N71edDo6OjLz+0qWtXFUgrgWFrIflFq/GX9p5bwMLxwRmoCGjVYEitxwo3CBXwnMQEmwM752pItku",
	"19lcyI2RI2FDUarh1XjVaMNbJZcD3oUgaaXTHeeW3y61V6AJ9KA1E6ghA9zUlphyS2B2UHz1RRZofNDD",
	"17dAbbJ+XTG6jzQ7qfLtFuu1wib0akCyogCKpL645SqYCXdv87Uwqb4cHs/Ty+iuvl2CSW81n/C6A/jy",
	"cvnPAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
