// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lookups.sql

package db

import (
	"context"
)

const clearProductImageSource = `-- name: ClearProductImageSource :exec
UPDATE products
SET image_source_url = NULL, updated_at = ?
WHERE id = ? AND image_source_url = ?
`

type ClearProductImageSourceParams struct {
	UpdatedAt      string
	ID             string
	ImageSourceUrl *string
}

func (q *Queries) ClearProductImageSource(ctx context.Context, arg ClearProductImageSourceParams) error {
	_, err := q.db.ExecContext(ctx, clearProductImageSource, arg.UpdatedAt, arg.ID, arg.ImageSourceUrl)
	return err
}

const firstProductBarcode = `-- name: FirstProductBarcode :one
SELECT code FROM barcodes
WHERE product_id = ?
ORDER BY code
LIMIT 1
`

func (q *Queries) FirstProductBarcode(ctx context.Context, productID string) (string, error) {
	row := q.db.QueryRowContext(ctx, firstProductBarcode, productID)
	var code string
	err := row.Scan(&code)
	return code, err
}

const getLookup = `-- name: GetLookup :one
SELECT code, source, found, payload, fetched_at FROM lookups
WHERE code = ? AND source = ?
`

type GetLookupParams struct {
	Code   string
	Source string
}

func (q *Queries) GetLookup(ctx context.Context, arg GetLookupParams) (Lookup, error) {
	row := q.db.QueryRowContext(ctx, getLookup, arg.Code, arg.Source)
	var i Lookup
	err := row.Scan(
		&i.Code,
		&i.Source,
		&i.Found,
		&i.Payload,
		&i.FetchedAt,
	)
	return i, err
}

const listPendingProducts = `-- name: ListPendingProducts :many
SELECT id FROM products
WHERE lookup_state = 'pending'
ORDER BY created_at, id
LIMIT ?
`

func (q *Queries) ListPendingProducts(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPendingProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsWithoutImage = `-- name: ListProductsWithoutImage :many
SELECT id, image_source_url FROM products
WHERE image_source_url IS NOT NULL AND image_file IS NULL
ORDER BY created_at, id
LIMIT ?
`

type ListProductsWithoutImageRow struct {
	ID             string
	ImageSourceUrl *string
}

func (q *Queries) ListProductsWithoutImage(ctx context.Context, limit int64) ([]ListProductsWithoutImageRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsWithoutImage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsWithoutImageRow
	for rows.Next() {
		var i ListProductsWithoutImageRow
		if err := rows.Scan(&i.ID, &i.ImageSourceUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductImageFile = `-- name: SetProductImageFile :execrows
UPDATE products
SET image_file = ?, updated_at = ?
WHERE id = ? AND image_source_url = ?
`

type SetProductImageFileParams struct {
	ImageFile      *string
	UpdatedAt      string
	ID             string
	ImageSourceUrl *string
}

func (q *Queries) SetProductImageFile(ctx context.Context, arg SetProductImageFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProductImageFile,
		arg.ImageFile,
		arg.UpdatedAt,
		arg.ID,
		arg.ImageSourceUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProductLookup = `-- name: UpdateProductLookup :exec
UPDATE products
SET name = ?, brand = ?, package_size = ?, origin = ?, image_source_url = ?,
    lookup_state = ?, updated_at = ?
WHERE id = ?
`

type UpdateProductLookupParams struct {
	Name           string
	Brand          *string
	PackageSize    *string
	Origin         string
	ImageSourceUrl *string
	LookupState    string
	UpdatedAt      string
	ID             string
}

func (q *Queries) UpdateProductLookup(ctx context.Context, arg UpdateProductLookupParams) error {
	_, err := q.db.ExecContext(ctx, updateProductLookup,
		arg.Name,
		arg.Brand,
		arg.PackageSize,
		arg.Origin,
		arg.ImageSourceUrl,
		arg.LookupState,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertLookup = `-- name: UpsertLookup :exec
INSERT INTO lookups (code, source, found, payload, fetched_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (code, source) DO UPDATE SET
    found = excluded.found,
    payload = excluded.payload,
    fetched_at = excluded.fetched_at
`

type UpsertLookupParams struct {
	Code      string
	Source    string
	Found     int64
	Payload   *string
	FetchedAt string
}

func (q *Queries) UpsertLookup(ctx context.Context, arg UpsertLookupParams) error {
	_, err := q.db.ExecContext(ctx, upsertLookup,
		arg.Code,
		arg.Source,
		arg.Found,
		arg.Payload,
		arg.FetchedAt,
	)
	return err
}
