// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lookups.sql

package db

import (
	"context"
)

const getLookup = `-- name: GetLookup :one
SELECT code, source, found, payload, fetched_at FROM lookups
WHERE code = ? AND source = ?
`

type GetLookupParams struct {
	Code   string
	Source string
}

func (q *Queries) GetLookup(ctx context.Context, arg GetLookupParams) (Lookup, error) {
	row := q.db.QueryRowContext(ctx, getLookup, arg.Code, arg.Source)
	var i Lookup
	err := row.Scan(
		&i.Code,
		&i.Source,
		&i.Found,
		&i.Payload,
		&i.FetchedAt,
	)
	return i, err
}

const upsertLookup = `-- name: UpsertLookup :exec
INSERT INTO lookups (code, source, found, payload, fetched_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (code, source) DO UPDATE SET
    found = excluded.found,
    payload = excluded.payload,
    fetched_at = excluded.fetched_at
`

type UpsertLookupParams struct {
	Code      string
	Source    string
	Found     int64
	Payload   *string
	FetchedAt string
}

func (q *Queries) UpsertLookup(ctx context.Context, arg UpsertLookupParams) error {
	_, err := q.db.ExecContext(ctx, upsertLookup,
		arg.Code,
		arg.Source,
		arg.Found,
		arg.Payload,
		arg.FetchedAt,
	)
	return err
}
