// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
)

const createMember = `-- name: CreateMember :exec
INSERT INTO members (id, name, created_at)
VALUES (?, ?, ?)
`

type CreateMemberParams struct {
	ID        string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) error {
	_, err := q.db.ExecContext(ctx, createMember, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, name, created_at FROM members
WHERE id = ?
`

func (q *Queries) GetMember(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i Member
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, name, created_at FROM members
ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
