// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Member struct {
	ID        string
	Name      string
	CreatedAt string
}

type Session struct {
	TokenHash  string
	MemberID   *string
	CreatedAt  string
	LastSeenAt string
	ExpiresAt  string
}

type Setting struct {
	Key   string
	Value string
}
