// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movements.sql

package db

import (
	"context"
)

const insertMovement = `-- name: InsertMovement :one
INSERT INTO movements (id, product_id, kind, delta, stock_after, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, product_id, kind, delta, stock_after, barcode, reverses_id, idempotency_key, request_hash, created_at
`

type InsertMovementParams struct {
	ID         string
	ProductID  string
	Kind       string
	Delta      int64
	StockAfter int64
	CreatedAt  string
}

func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) (Movement, error) {
	row := q.db.QueryRowContext(ctx, insertMovement,
		arg.ID,
		arg.ProductID,
		arg.Kind,
		arg.Delta,
		arg.StockAfter,
		arg.CreatedAt,
	)
	var i Movement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Kind,
		&i.Delta,
		&i.StockAfter,
		&i.Barcode,
		&i.ReversesID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET stock = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at
`

type UpdateProductStockParams struct {
	Stock     int64
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductStock, arg.Stock, arg.UpdatedAt, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PackageSize,
		&i.Stock,
		&i.Target,
		&i.MinStock,
		&i.Note,
		&i.Origin,
		&i.LookupState,
		&i.NeedsReview,
		&i.ImageSourceUrl,
		&i.ImageFile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
