// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movements.sql

package db

import (
	"context"
)

const getMovement = `-- name: GetMovement :one
SELECT id, product_id, kind, delta, stock_after, barcode, reverses_id, idempotency_key, request_hash, created_at FROM movements
WHERE id = ?
`

func (q *Queries) GetMovement(ctx context.Context, id string) (Movement, error) {
	row := q.db.QueryRowContext(ctx, getMovement, id)
	var i Movement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Kind,
		&i.Delta,
		&i.StockAfter,
		&i.Barcode,
		&i.ReversesID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
	)
	return i, err
}

const getMovementByIdempotencyKey = `-- name: GetMovementByIdempotencyKey :one
SELECT id, product_id, kind, delta, stock_after, barcode, reverses_id, idempotency_key, request_hash, created_at FROM movements
WHERE idempotency_key = ?
`

func (q *Queries) GetMovementByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Movement, error) {
	row := q.db.QueryRowContext(ctx, getMovementByIdempotencyKey, idempotencyKey)
	var i Movement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Kind,
		&i.Delta,
		&i.StockAfter,
		&i.Barcode,
		&i.ReversesID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertMovement = `-- name: InsertMovement :one
INSERT INTO movements (id, product_id, kind, delta, stock_after, barcode,
    reverses_id, idempotency_key, request_hash, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, product_id, kind, delta, stock_after, barcode, reverses_id, idempotency_key, request_hash, created_at
`

type InsertMovementParams struct {
	ID             string
	ProductID      string
	Kind           string
	Delta          int64
	StockAfter     int64
	Barcode        *string
	ReversesID     *string
	IdempotencyKey *string
	RequestHash    *string
	CreatedAt      string
}

func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) (Movement, error) {
	row := q.db.QueryRowContext(ctx, insertMovement,
		arg.ID,
		arg.ProductID,
		arg.Kind,
		arg.Delta,
		arg.StockAfter,
		arg.Barcode,
		arg.ReversesID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.CreatedAt,
	)
	var i Movement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Kind,
		&i.Delta,
		&i.StockAfter,
		&i.Barcode,
		&i.ReversesID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
	)
	return i, err
}

const isMovementReversed = `-- name: IsMovementReversed :one
SELECT EXISTS (SELECT 1 FROM movements WHERE reverses_id = ?)
`

func (q *Queries) IsMovementReversed(ctx context.Context, reversesID *string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isMovementReversed, reversesID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMovements = `-- name: ListMovements :many
SELECT id, product_id, kind, delta, stock_after, barcode, reverses_id, idempotency_key, request_hash, created_at FROM movements
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) ListMovements(ctx context.Context, limit int64) ([]Movement, error) {
	rows, err := q.db.QueryContext(ctx, listMovements, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movement
	for rows.Next() {
		var i Movement
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Kind,
			&i.Delta,
			&i.StockAfter,
			&i.Barcode,
			&i.ReversesID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsBefore = `-- name: ListMovementsBefore :many
SELECT id, product_id, kind, delta, stock_after, barcode, reverses_id, idempotency_key, request_hash, created_at FROM movements
WHERE id < ?
ORDER BY id DESC
LIMIT ?
`

type ListMovementsBeforeParams struct {
	ID    string
	Limit int64
}

func (q *Queries) ListMovementsBefore(ctx context.Context, arg ListMovementsBeforeParams) ([]Movement, error) {
	rows, err := q.db.QueryContext(ctx, listMovementsBefore, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movement
	for rows.Next() {
		var i Movement
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Kind,
			&i.Delta,
			&i.StockAfter,
			&i.Barcode,
			&i.ReversesID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductMovements = `-- name: ListProductMovements :many
SELECT id, product_id, kind, delta, stock_after, barcode, reverses_id, idempotency_key, request_hash, created_at FROM movements
WHERE product_id = ?
ORDER BY id DESC
LIMIT ?
`

type ListProductMovementsParams struct {
	ProductID string
	Limit     int64
}

func (q *Queries) ListProductMovements(ctx context.Context, arg ListProductMovementsParams) ([]Movement, error) {
	rows, err := q.db.QueryContext(ctx, listProductMovements, arg.ProductID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movement
	for rows.Next() {
		var i Movement
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Kind,
			&i.Delta,
			&i.StockAfter,
			&i.Barcode,
			&i.ReversesID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductMovementsBefore = `-- name: ListProductMovementsBefore :many
SELECT id, product_id, kind, delta, stock_after, barcode, reverses_id, idempotency_key, request_hash, created_at FROM movements
WHERE product_id = ? AND id < ?
ORDER BY id DESC
LIMIT ?
`

type ListProductMovementsBeforeParams struct {
	ProductID string
	ID        string
	Limit     int64
}

func (q *Queries) ListProductMovementsBefore(ctx context.Context, arg ListProductMovementsBeforeParams) ([]Movement, error) {
	rows, err := q.db.QueryContext(ctx, listProductMovementsBefore, arg.ProductID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movement
	for rows.Next() {
		var i Movement
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Kind,
			&i.Delta,
			&i.StockAfter,
			&i.Barcode,
			&i.ReversesID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET stock = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at
`

type UpdateProductStockParams struct {
	Stock     int64
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductStock, arg.Stock, arg.UpdatedAt, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PackageSize,
		&i.Stock,
		&i.Target,
		&i.MinStock,
		&i.Note,
		&i.Origin,
		&i.LookupState,
		&i.NeedsReview,
		&i.ImageSourceUrl,
		&i.ImageFile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
