// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
)

const deleteOutboxEntriesBefore = `-- name: DeleteOutboxEntriesBefore :execrows
DELETE FROM outbox
WHERE created_at < ?
`

func (q *Queries) DeleteOutboxEntriesBefore(ctx context.Context, createdAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOutboxEntriesBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOutboxEntry = `-- name: DeleteOutboxEntry :exec
DELETE FROM outbox
WHERE seq = ?
`

func (q *Queries) DeleteOutboxEntry(ctx context.Context, seq int64) error {
	_, err := q.db.ExecContext(ctx, deleteOutboxEntry, seq)
	return err
}

const insertOutboxEntry = `-- name: InsertOutboxEntry :exec
INSERT INTO outbox (topic, payload, created_at)
VALUES (?, ?, ?)
`

type InsertOutboxEntryParams struct {
	Topic     string
	Payload   string
	CreatedAt string
}

func (q *Queries) InsertOutboxEntry(ctx context.Context, arg InsertOutboxEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxEntry, arg.Topic, arg.Payload, arg.CreatedAt)
	return err
}

const listOutboxEntries = `-- name: ListOutboxEntries :many
SELECT seq, topic, payload, created_at, attempts, last_error FROM outbox
ORDER BY seq
LIMIT ?
`

func (q *Queries) ListOutboxEntries(ctx context.Context, limit int64) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, listOutboxEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.Seq,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordOutboxFailure = `-- name: RecordOutboxFailure :exec
UPDATE outbox
SET attempts = attempts + 1, last_error = ?
WHERE seq = ?
`

type RecordOutboxFailureParams struct {
	LastError *string
	Seq       int64
}

func (q *Queries) RecordOutboxFailure(ctx context.Context, arg RecordOutboxFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordOutboxFailure, arg.LastError, arg.Seq)
	return err
}
