// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at FROM products
WHERE id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PackageSize,
		&i.Stock,
		&i.Target,
		&i.MinStock,
		&i.Note,
		&i.Origin,
		&i.LookupState,
		&i.NeedsReview,
		&i.ImageSourceUrl,
		&i.ImageFile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBarcodes = `-- name: ListBarcodes :many
SELECT code, product_id, units, created_at FROM barcodes
ORDER BY code
`

func (q *Queries) ListBarcodes(ctx context.Context) ([]Barcode, error) {
	rows, err := q.db.QueryContext(ctx, listBarcodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Barcode
	for rows.Next() {
		var i Barcode
		if err := rows.Scan(
			&i.Code,
			&i.ProductID,
			&i.Units,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductBarcodes = `-- name: ListProductBarcodes :many
SELECT code, product_id, units, created_at FROM barcodes
WHERE product_id = ?
ORDER BY code
`

func (q *Queries) ListProductBarcodes(ctx context.Context, productID string) ([]Barcode, error) {
	rows, err := q.db.QueryContext(ctx, listProductBarcodes, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Barcode
	for rows.Next() {
		var i Barcode
		if err := rows.Scan(
			&i.Code,
			&i.ProductID,
			&i.Units,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at FROM products
ORDER BY name COLLATE NOCASE, id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.PackageSize,
			&i.Stock,
			&i.Target,
			&i.MinStock,
			&i.Note,
			&i.Origin,
			&i.LookupState,
			&i.NeedsReview,
			&i.ImageSourceUrl,
			&i.ImageFile,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
