// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
)

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products
WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProductBarcode = `-- name: DeleteProductBarcode :execrows
DELETE FROM barcodes
WHERE code = ? AND product_id = ?
`

type DeleteProductBarcodeParams struct {
	Code      string
	ProductID string
}

func (q *Queries) DeleteProductBarcode(ctx context.Context, arg DeleteProductBarcodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProductBarcode, arg.Code, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBarcode = `-- name: GetBarcode :one
SELECT code, product_id, units, created_at FROM barcodes
WHERE code = ?
`

func (q *Queries) GetBarcode(ctx context.Context, code string) (Barcode, error) {
	row := q.db.QueryRowContext(ctx, getBarcode, code)
	var i Barcode
	err := row.Scan(
		&i.Code,
		&i.ProductID,
		&i.Units,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at, marked FROM products
WHERE id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PackageSize,
		&i.Stock,
		&i.Target,
		&i.MinStock,
		&i.Note,
		&i.Origin,
		&i.LookupState,
		&i.NeedsReview,
		&i.ImageSourceUrl,
		&i.ImageFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Marked,
	)
	return i, err
}

const insertBarcode = `-- name: InsertBarcode :one
INSERT INTO barcodes (code, product_id, units, created_at)
VALUES (?, ?, ?, ?)
RETURNING code, product_id, units, created_at
`

type InsertBarcodeParams struct {
	Code      string
	ProductID string
	Units     int64
	CreatedAt string
}

func (q *Queries) InsertBarcode(ctx context.Context, arg InsertBarcodeParams) (Barcode, error) {
	row := q.db.QueryRowContext(ctx, insertBarcode,
		arg.Code,
		arg.ProductID,
		arg.Units,
		arg.CreatedAt,
	)
	var i Barcode
	err := row.Scan(
		&i.Code,
		&i.ProductID,
		&i.Units,
		&i.CreatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (id, name, brand, package_size, target, min_stock, note,
    origin, lookup_state, needs_review, image_source_url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at, marked
`

type InsertProductParams struct {
	ID             string
	Name           string
	Brand          *string
	PackageSize    *string
	Target         int64
	MinStock       *int64
	Note           *string
	Origin         string
	LookupState    string
	NeedsReview    int64
	ImageSourceUrl *string
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.ID,
		arg.Name,
		arg.Brand,
		arg.PackageSize,
		arg.Target,
		arg.MinStock,
		arg.Note,
		arg.Origin,
		arg.LookupState,
		arg.NeedsReview,
		arg.ImageSourceUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PackageSize,
		&i.Stock,
		&i.Target,
		&i.MinStock,
		&i.Note,
		&i.Origin,
		&i.LookupState,
		&i.NeedsReview,
		&i.ImageSourceUrl,
		&i.ImageFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Marked,
	)
	return i, err
}

const listBarcodes = `-- name: ListBarcodes :many
SELECT code, product_id, units, created_at FROM barcodes
ORDER BY code
`

func (q *Queries) ListBarcodes(ctx context.Context) ([]Barcode, error) {
	rows, err := q.db.QueryContext(ctx, listBarcodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Barcode
	for rows.Next() {
		var i Barcode
		if err := rows.Scan(
			&i.Code,
			&i.ProductID,
			&i.Units,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductBarcodes = `-- name: ListProductBarcodes :many
SELECT code, product_id, units, created_at FROM barcodes
WHERE product_id = ?
ORDER BY code
`

func (q *Queries) ListProductBarcodes(ctx context.Context, productID string) ([]Barcode, error) {
	rows, err := q.db.QueryContext(ctx, listProductBarcodes, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Barcode
	for rows.Next() {
		var i Barcode
		if err := rows.Scan(
			&i.Code,
			&i.ProductID,
			&i.Units,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at, marked FROM products
ORDER BY name COLLATE NOCASE, id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.PackageSize,
			&i.Stock,
			&i.Target,
			&i.MinStock,
			&i.Note,
			&i.Origin,
			&i.LookupState,
			&i.NeedsReview,
			&i.ImageSourceUrl,
			&i.ImageFile,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Marked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveProductBarcodes = `-- name: MoveProductBarcodes :exec
UPDATE barcodes
SET product_id = ?1
WHERE product_id = ?2
`

type MoveProductBarcodesParams struct {
	TargetID string
	SourceID string
}

func (q *Queries) MoveProductBarcodes(ctx context.Context, arg MoveProductBarcodesParams) error {
	_, err := q.db.ExecContext(ctx, moveProductBarcodes, arg.TargetID, arg.SourceID)
	return err
}

const setProductImage = `-- name: SetProductImage :one
UPDATE products
SET image_file = ?, image_source_url = NULL, updated_at = ?
WHERE id = ?
RETURNING id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at, marked
`

type SetProductImageParams struct {
	ImageFile *string
	UpdatedAt string
	ID        string
}

func (q *Queries) SetProductImage(ctx context.Context, arg SetProductImageParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, setProductImage, arg.ImageFile, arg.UpdatedAt, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PackageSize,
		&i.Stock,
		&i.Target,
		&i.MinStock,
		&i.Note,
		&i.Origin,
		&i.LookupState,
		&i.NeedsReview,
		&i.ImageSourceUrl,
		&i.ImageFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Marked,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = ?, brand = ?, package_size = ?, target = ?, min_stock = ?, note = ?,
    needs_review = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at, marked
`

type UpdateProductParams struct {
	Name        string
	Brand       *string
	PackageSize *string
	Target      int64
	MinStock    *int64
	Note        *string
	NeedsReview int64
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Name,
		arg.Brand,
		arg.PackageSize,
		arg.Target,
		arg.MinStock,
		arg.Note,
		arg.NeedsReview,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PackageSize,
		&i.Stock,
		&i.Target,
		&i.MinStock,
		&i.Note,
		&i.Origin,
		&i.LookupState,
		&i.NeedsReview,
		&i.ImageSourceUrl,
		&i.ImageFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Marked,
	)
	return i, err
}
