// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopping.sql

package db

import (
	"context"
)

const setProductMarked = `-- name: SetProductMarked :one
UPDATE products
SET marked = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at, marked, crate_size
`

type SetProductMarkedParams struct {
	Marked    int64
	UpdatedAt string
	ID        string
}

func (q *Queries) SetProductMarked(ctx context.Context, arg SetProductMarkedParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, setProductMarked, arg.Marked, arg.UpdatedAt, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PackageSize,
		&i.Stock,
		&i.Target,
		&i.MinStock,
		&i.Note,
		&i.Origin,
		&i.LookupState,
		&i.NeedsReview,
		&i.ImageSourceUrl,
		&i.ImageFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Marked,
		&i.CrateSize,
	)
	return i, err
}
