// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopping.sql

package db

import (
	"context"
)

const listShoppingSnapshotProducts = `-- name: ListShoppingSnapshotProducts :many
SELECT id, name, stock, target, min_stock, marked, crate_size FROM products
WHERE target > 0 OR marked = 1
ORDER BY name COLLATE NOCASE, id
`

type ListShoppingSnapshotProductsRow struct {
	ID        string
	Name      string
	Stock     int64
	Target    int64
	MinStock  *int64
	Marked    int64
	CrateSize *int64
}

func (q *Queries) ListShoppingSnapshotProducts(ctx context.Context) ([]ListShoppingSnapshotProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingSnapshotProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShoppingSnapshotProductsRow
	for rows.Next() {
		var i ListShoppingSnapshotProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Stock,
			&i.Target,
			&i.MinStock,
			&i.Marked,
			&i.CrateSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductMarked = `-- name: SetProductMarked :one
UPDATE products
SET marked = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, brand, package_size, stock, target, min_stock, note, origin, lookup_state, needs_review, image_source_url, image_file, created_at, updated_at, marked, crate_size
`

type SetProductMarkedParams struct {
	Marked    int64
	UpdatedAt string
	ID        string
}

func (q *Queries) SetProductMarked(ctx context.Context, arg SetProductMarkedParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, setProductMarked, arg.Marked, arg.UpdatedAt, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.PackageSize,
		&i.Stock,
		&i.Target,
		&i.MinStock,
		&i.Note,
		&i.Origin,
		&i.LookupState,
		&i.NeedsReview,
		&i.ImageSourceUrl,
		&i.ImageFile,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Marked,
		&i.CrateSize,
	)
	return i, err
}
